// Auto-extracted artist/influence dataset, shared by explore.html and app.js
  var GEN=[
    {k:"roots",s:"Blues & roots",c:"#E0902A"},
    {k:"sixties",s:"60s / British Invasion",c:"#E14B44"},
    {k:"southern",s:"Southern & Americana",c:"#8B5E34"},
    {k:"garage",s:"Garage & proto-punk",c:"#A23A2C"},
    {k:"hardrock",s:"Hard rock",c:"#C79A1E"},
    {k:"prog",s:"Prog rock",c:"#5E5AA8"},
    {k:"glam",s:"Glam",c:"#B24592"},
    {k:"metal",s:"Metal & thrash",c:"#6E6D67"},
    {k:"punk",s:"Punk, hardcore, emo",c:"#CE3E6B"},
    {k:"postpunk",s:"Post-punk / new wave",c:"#7B70E2"},
    {k:"experimental",s:"Krautrock / industrial",c:"#5477A0"},
    {k:"noise",s:"Noise & shoegaze",c:"#3B87D6"},
    {k:"college",s:"College / power pop",c:"#2E9E86"},
    {k:"grunge",s:"Grunge",c:"#6FA02A"},
    {k:"indie",s:"Indie & art-rock",c:"#C964A4"}
  ];

  var RAW={
    muddywaters:["Muddy Waters",1950,"roots","Electric Chicago blues - the bedrock rock was built on.",[],0,[["Landmark","The Best of Muddy Waters (1958)"],["Live peak","At Newport 1960"]]],
    howlinwolf:["Howlin' Wolf",1951,"roots","Growling, primal Chicago blues.",[],0,[["Start","Moanin' in the Moonlight (1959)"],["Loved","Howlin' Wolf ('Rockin' Chair', 1962)"]]],
    chuckberry:["Chuck Berry",1955,"roots","The blueprint for rock guitar and songwriting.",["muddywaters"],0,[["Start","The Great Twenty-Eight (comp.)"]]],
    littlerichard:["Little Richard",1956,"roots","Wild, screaming, foundational rock and roll.",[],0,[["Start","Here's Little Richard (1957)"]]],
    elvis:["Elvis Presley",1956,"roots","The face that turned rock and roll into a phenomenon.",[],0,[["Start","Elvis Presley (1956)"],["Loved","The Sun Sessions (comp.)"]]],
    buddyholly:["Buddy Holly",1957,"roots","Melodic, self-written rock and roll that shaped the Beatles.",[],0,[["Start","The 'Chirping' Crickets (1957)"]]],
    bodiddley:["Bo Diddley",1955,"roots","His signature beat echoes through decades of rock.",["muddywaters"],0,[["Start","Bo Diddley / Go Bo Diddley (1958)"]]],
    linkwray:["Link Wray",1958,"roots","'Rumble' invented the menacing distorted-guitar tone.",[],0,[["Essential","'Rumble' and other early singles"]]],
    beatles:["The Beatles",1963,"sixties","Evolved from simple pop to studio art faster than anyone.",["chuckberry","littlerichard","elvis","buddyholly"],0,[["Start","Rubber Soul (1965)"],["Best","Revolver (1966)"],["Loved","Abbey Road (1969)"]]],
    stones:["The Rolling Stones",1964,"sixties","Took American blues and made it swaggering rock.",["chuckberry","bodiddley","muddywaters"],0,[["Best","Let It Bleed (1969)"],["Loved","Exile on Main St. (1972)"]]],
    kinks:["The Kinks",1964,"sixties","'You Really Got Me' helped invent the hard-rock riff.",["chuckberry"],0,[["Best","Village Green Preservation Society (1968)"],["Start","The Kink Kronikles (comp.)"]]],
    who:["The Who",1965,"sixties","Explosive and powerful, pointing straight at hard rock.",[],0,[["Best","Who's Next (1971)"],["Live","Live at Leeds (1970)"]]],
    dylan:["Bob Dylan",1965,"sixties","Plugged folk into electric rock and made lyrics literary.",[],0,[["Best","Highway 61 Revisited (1965)"],["Loved","Blonde on Blonde (1966)"]]],
    byrds:["The Byrds",1965,"sixties","Jangly, chiming folk rock.",["dylan","beatles"],0,[["Start","Mr. Tambourine Man (1965)"],["Loved","Sweetheart of the Rodeo (1968)"]]],
    hendrix:["Jimi Hendrix",1967,"sixties","Redefined what an electric guitar could do.",["muddywaters"],0,[["Start","Are You Experienced (1967)"],["Best","Electric Ladyland (1968)"]]],
    doors:["The Doors",1967,"sixties","Dark, poetic psychedelic rock.",[],0,[["Start","The Doors (1967)"],["Loved","L.A. Woman (1971)"]]],
    beachboys:["The Beach Boys",1966,"sixties","Studio-pop genius that pushed the Beatles further.",["chuckberry"],0,[["Essential","Pet Sounds (1966)"]]],
    yardbirds:["The Yardbirds",1965,"sixties","The blues-rock incubator for Clapton, Beck, and Page.",["stones","howlinwolf"],0,[["Best","Roger the Engineer (1966)"],["Comp","Ultimate! (best-of)"]],"A guitar academy: <b>Eric Clapton</b>, then Jeff Beck, then <b>Jimmy Page</b> all passed through — Page carried it straight into Led Zeppelin."],
    velvet:["The Velvet Underground",1967,"garage","Barely sold records; launched punk, post-punk, noise, and indie.",[],0,[["Start","The Velvet Underground & Nico (1967)"],["Best","White Light/White Heat (1968)"],["Loved","The Velvet Underground (1969)"]],"<b>Lou Reed</b> and <b>John Cale</b> — two of rock's most influential figures — with Nico."],
    stooges:["The Stooges",1969,"garage","The primal fountainhead of punk.",[],0,[["Start","The Stooges (1969)"],["Best","Fun House (1970)"],["Loved","Raw Power (1973)"]],"Fronted by <b>Iggy Pop</b>, the wild man who invented the punk frontman."],
    mc5:["MC5",1969,"garage","Proto-punk firebrands, loud and revolutionary.",[],0,[["Essential","Kick Out the Jams (1969)"]]],
    sonics:["The Sonics",1965,"garage","Screaming garage rock at punk energy, years early.",["chuckberry","littlerichard","linkwray"],0,[["Start","Here Are The Sonics (1965)"],["Loved","Boom (1966)"]]],
    allmanbros:["The Allman Brothers Band",1971,"southern","Twin-guitar Southern jam-rock pioneers.",["muddywaters"],0,[["Essential","At Fillmore East (1971)"]]],
    lynyrdskynyrd:["Lynyrd Skynyrd",1974,"southern","The definitive Southern rock band.",["stones","allmanbros"],0,[["Start","(Pronounced 'Leh-nerd 'Skin-nerd) (1973)"],["Loved","Second Helping (1974)"]]],
    ccr:["Creedence Clearwater Revival",1969,"southern","Swampy, tight American roots rock.",["chuckberry"],0,[["Start","Chronicle (comp.)"],["Best","Cosmo's Factory (1970)"]]],
    eagles:["Eagles",1975,"southern","Smooth, huge country-rock harmony.",["byrds"],0,[["Best","Hotel California (1976)"],["Comp","Their Greatest Hits 1971-1975"]]],
    tompetty:["Tom Petty",1977,"southern","Heartland rock built on jangle and hooks.",["byrds","stones"],0,[["Loved","Full Moon Fever (1989)"],["Best","Wildflowers (1994)"]]],
    springsteen:["Bruce Springsteen",1975,"southern","Earnest, working-class heartland rock.",["dylan","stones"],0,[["Start","Born to Run (1975)"],["Best","Darkness on the Edge of Town (1978)"],["Loved","Born in the U.S.A. (1984)"]]],
    gratefuldead:["Grateful Dead",1970,"southern","The improvisational heart of the jam-band world.",["chuckberry"],0,[["Start","American Beauty (1970)"],["Live","Live/Dead (1969)"]]],
    ledzep:["Led Zeppelin",1969,"hardrock","Blues amplified into towering hard rock.",["yardbirds","stones","who","muddywaters"],0,[["Loved","IV (1971)"],["Best","Physical Graffiti (1975)"],["Start","II (1969)"]],"Built by <b>Jimmy Page</b> out of the final days of the Yardbirds."],
    sabbath:["Black Sabbath",1970,"metal","The origin point of heavy metal.",[],0,[["Start","Paranoid (1970)"],["Best","Master of Reality (1971)"],["Loved","Black Sabbath (1970)"]],"Fronted by <b>Ozzy Osbourne</b> until 1979, then by <b>Ronnie James Dio</b>."],
    deeppurple:["Deep Purple",1970,"hardrock","Loud, virtuosic proto-hard-rock.",[],0,[["Essential","Machine Head (1972)"],["Live","Made in Japan (1972)"]]],
    cream:["Cream",1967,"hardrock","Blues-rock power trio, guitar-hero territory.",["yardbirds","howlinwolf"],0,[["Best","Disraeli Gears (1967)"],["Loved","Wheels of Fire (1968)"]],"<b>Eric Clapton</b> came here straight from the Yardbirds."],
    pinkfloyd:["Pink Floyd",1973,"prog","Psychedelia turned into vast progressive soundscapes.",[],0,[["Start","The Dark Side of the Moon (1973)"],["Loved","Wish You Were Here (1975)"],["Epic","The Wall (1979)"]]],
    kingcrimson:["King Crimson",1969,"prog","The ambitious, complex heart of prog rock.",[],0,[["Start","In the Court of the Crimson King (1969)"],["Best","Red (1974)"]]],
    yes:["Yes",1972,"prog","Grand, intricate progressive rock.",["kingcrimson"],0,[["Best","Close to the Edge (1972)"],["Loved","Fragile (1971)"]]],
    genesis:["Genesis",1974,"prog","Theatrical prog that later became pop.",["kingcrimson"],0,[["Best","Selling England by the Pound (1973)"],["Epic","The Lamb Lies Down on Broadway (1974)"]],"<b>Peter Gabriel</b> led the prog years; <b>Phil Collins</b> steered the pop era."],
    bowie:["David Bowie",1972,"glam","Reinvention as an art form - folk, glam, soul, art-rock.",["velvet","stones","can"],0,[["Start","Ziggy Stardust (1972)"],["Best","Low (1977)"],["Loved","Hunky Dory (1971)"]],"<b>David Bowie</b> himself — rock's great chameleon."],
    trex:["T. Rex",1971,"glam","Glam rock's stomping, hooky template.",[],0,[["Essential","Electric Warrior (1971)"]]],
    roxymusic:["Roxy Music",1972,"glam","Art-glam that shaped Bowie's world and post-punk.",["velvet"],0,[["Start","Roxy Music (1972)"],["Best","For Your Pleasure (1973)"],["Loved","Avalon (1982)"]],"Featured <b>Brian Eno</b>, later a legendary producer and solo artist."],
    queen:["Queen",1975,"hardrock","Operatic hard rock with limitless range.",["who","ledzep"],0,[["Best","A Night at the Opera (1975)"],["Loved","A Day at the Races (1976)"]]],
    acdc:["AC/DC",1976,"hardrock","Stripped-down, riff-driven hard rock perfection.",["stones"],0,[["Best","Back in Black (1980)"],["Loved","Highway to Hell (1979)"]]],
    aerosmith:["Aerosmith",1975,"hardrock","Sleazy, bluesy American hard rock.",["stones","ledzep"],0,[["Best","Toys in the Attic (1975)"],["Loved","Rocks (1976)"]]],
    rush:["Rush",1976,"prog","Virtuosic prog that also rocked hard.",["kingcrimson","who"],0,[["Best","Moving Pictures (1981)"],["Epic","2112 (1976)"]]],
    thinlizzy:["Thin Lizzy",1976,"hardrock","Twin-guitar hard rock, hugely influential on metal.",["stones"],0,[["Start","Jailbreak (1976)"],["Live","Live and Dangerous (1978)"]]],
    nydolls:["New York Dolls",1973,"glam","Trashy glam-punk bridging the Stooges and punk.",["stooges"],0,[["Essential","New York Dolls (1973)"]]],
    gunsnroses:["Guns N' Roses",1987,"hardrock","Sleazy, dangerous hard rock at stadium scale.",["aerosmith","acdc"],0,[["Essential","Appetite for Destruction (1987)"]],"<b>Axl Rose</b> and <b>Slash</b>; Slash and others later formed Velvet Revolver with STP's Scott Weiland."],
    motleycrue:["Mötley Crüe",1983,"glam","Glam-metal excess and hooks.",["aerosmith"],0,[["Best","Shout at the Devil (1983)"],["Loved","Dr. Feelgood (1989)"]]],
    defleppard:["Def Leppard",1983,"glam","Polished, anthemic glam metal.",["ironmaiden","queen"],0,[["Essential","Hysteria (1987)"],["Loved","Pyromania (1983)"]]],
    bigstar:["Big Star",1972,"college","Sold nothing; wrote the template for melodic guitar-pop.",["beatles","kinks"],0,[["Start","#1 Record (1972)"],["Best","Radio City (1974)"],["Cult","Third/Sister Lovers (1978)"]],"<b>Alex Chilton</b>, teenage star of the Box Tops, made his masterpiece here in obscurity."],
    neilyoung:["Neil Young",1970,"southern","The folkie who also made ragged, proto-grunge noise.",[],0,[["Start","After the Gold Rush (1970)"],["Best","Everybody Knows This Is Nowhere (1969)"],["Raw","Ragged Glory (1990)"]]],
    can:["Can",1971,"experimental","Hypnotic, motorik krautrock.",[],0,[["Best","Tago Mago (1971)"],["Loved","Ege Bamyasi (1972)"]]],
    neu:["Neu!",1972,"experimental","The motorik beat that reshaped rock.",[],0,[["Essential","Neu! (1972)"]]],
    kraftwerk:["Kraftwerk",1974,"experimental","Electronic pioneers who influenced everyone downstream.",[],0,[["Start","Trans-Europe Express (1977)"],["Best","The Man-Machine (1978)"]]],
    ministry:["Ministry",1989,"experimental","Harsh, mechanical industrial metal.",["kraftwerk"],0,[["Essential","The Land of Rape and Honey (1988)"],["Loved","Psalm 69 (1992)"]]],
    nin:["Nine Inch Nails",1994,"experimental","Industrial rock turned into bleak, huge art.",["bowie","ministry"],0,[["Best","The Downward Spiral (1994)"],["Start","Pretty Hate Machine (1989)"],["Loved","The Fragile (1999)"]],"Essentially the solo vehicle of <b>Trent Reznor</b>, now an Oscar-winning film composer."],
    motorhead:["Motörhead",1977,"metal","Punk speed plus metal volume - the bridge to thrash.",["stooges","sabbath"],0,[["Essential","Ace of Spades (1980)"],["Live","No Sleep 'til Hammersmith (1981)"]],"Driven by <b>Lemmy</b>, one of rock's most beloved figures."],
    judaspriest:["Judas Priest",1980,"metal","Defined metal's twin-guitar attack and leather look.",["sabbath","deeppurple"],0,[["Best","British Steel (1980)"],["Loved","Painkiller (1990)"]]],
    ramones:["Ramones",1976,"punk","Distilled rock to a buzzsaw and launched punk.",["stooges","velvet","nydolls","sonics"],0,[["Start","Ramones (1976)"],["Loved","Rocket to Russia (1977)"]]],
    pistols:["Sex Pistols",1977,"punk","The confrontational, nihilistic face of UK punk.",["stooges","nydolls"],0,[["Essential","Never Mind the Bollocks (1977)"]],"<b>John Lydon</b> (Johnny Rotten) walked out of here and straight into Public Image Ltd."],
    clash:["The Clash",1977,"punk","Punk that swallowed reggae, funk, and rockabilly whole.",["ramones","stooges"],0,[["Best","London Calling (1979)"],["Bold","Sandinista! (1980)"],["Start","The Clash (1977)"]]],
    television:["Television",1977,"punk","The arty, guitar-intricate end of CBGB.",["velvet"],0,[["Essential","Marquee Moon (1977)"]]],
    pattismith:["Patti Smith",1975,"punk","Poetry and punk fused at CBGB.",["velvet","stones"],0,[["Essential","Horses (1975)"]]],
    buzzcocks:["Buzzcocks",1978,"punk","Melodic, lovelorn punk with huge hooks.",["ramones","pistols"],0,[["Best","Singles Going Steady (comp.)"],["Loved","Another Music in a Different Kitchen (1978)"]]],
    damned:["The Damned",1977,"punk","First UK punk single; later gothy and wild.",["stooges","ramones"],0,[["Start","Damned Damned Damned (1977)"],["Best","Machine Gun Etiquette (1979)"]]],
    joydiv:["Joy Division",1979,"postpunk","Cold, intense, doomed - the blueprint for post-punk and goth.",["velvet","stooges","kraftwerk"],0,[["Start","Unknown Pleasures (1979)"],["Best","Closer (1980)"]],"After <b>Ian Curtis</b>'s death in 1980, the surviving members carried on as New Order."],
    wire:["Wire",1977,"postpunk","Punk turned minimal and conceptual.",["ramones","pistols"],0,[["Best","Pink Flag (1977)"],["Loved","Chairs Missing (1978)"]]],
    gangoffour:["Gang of Four",1979,"postpunk","Scratchy, funk-driven post-punk behind decades of indie.",[],0,[["Essential","Entertainment! (1979)"]]],
    talkingheads:["Talking Heads",1980,"postpunk","Jittery art-punk turned lush Afrobeat dance-rock.",["velvet"],0,[["Best","Remain in Light (1980)"],["Loved","Fear of Music (1979)"],["Live","Stop Making Sense (1984)"]],"Fronted by <b>David Byrne</b>; the rhythm section moonlighted as Tom Tom Club."],
    thecure:["The Cure",1982,"postpunk","Bleak and abrasive, then a source of shimmering pop.",[],0,[["Best","Disintegration (1989)"],["Dark","Pornography (1982)"],["Loved","The Head on the Door (1985)"]],"Built around <b>Robert Smith</b>, who also briefly played guitar in Siouxsie and the Banshees."],
    bauhaus:["Bauhaus",1979,"postpunk","Founders of goth rock.",["velvet","bowie"],0,[["Essential","In the Flat Field (1980)"]],"Singer <b>Peter Murphy</b>; other members later formed Love and Rockets."],
    siouxsie:["Siouxsie and the Banshees",1978,"postpunk","Dramatic, dark, foundational goth post-punk.",[],0,[["Best","Juju (1981)"],["Loved","Kaleidoscope (1980)"]],"<b>Robert Smith</b> of The Cure moonlighted as their guitarist for a spell."],
    devo:["Devo",1978,"postpunk","Jerky, satirical art-punk new wave.",["velvet"],0,[["Essential","Q: Are We Not Men? A: We Are Devo! (1978)"]]],
    blondie:["Blondie",1978,"postpunk","New wave that fused punk, pop, and disco.",["velvet","nydolls"],0,[["Essential","Parallel Lines (1978)"]]],
    thejam:["The Jam",1979,"postpunk","Mod-punk with a sharp, English eye.",["kinks","who"],0,[["Best","All Mod Cons (1978)"],["Loved","Sound Affects (1980)"]],"Led by <b>Paul Weller</b>, later of The Style Council and a solo career."],
    pil:["Public Image Ltd",1979,"postpunk","Lydon's dub-inflected post-punk after the Pistols.",["pistols"],0,[["Essential","Metal Box (1979)"]],"Formed by <b>John Lydon</b> the moment the Sex Pistols imploded."],
    thefall:["The Fall",1982,"postpunk","Relentless, abrasive, endlessly influential.",["velvet","stooges"],0,[["Best","Hex Enduction Hour (1982)"],["Loved","This Nation's Saving Grace (1985)"]],"Ruled with an iron fist by <b>Mark E. Smith</b> through 66 members over 40 years."],
    echobunnymen:["Echo & the Bunnymen",1984,"postpunk","Moody, atmospheric post-punk.",["velvet","doors"],0,[["Best","Ocean Rain (1984)"],["Loved","Heaven Up Here (1981)"]]],
    neworder:["New Order",1983,"postpunk","Joy Division reborn as electronic dance-rock.",["joydiv","kraftwerk"],0,[["Best","Power, Corruption & Lies (1983)"],["Loved","Technique (1989)"]],"The three surviving members of Joy Division, continuing without Ian Curtis."],
    blackflag:["Black Flag",1981,"punk","The relentless engine of American hardcore.",["stooges","ramones"],0,[["Essential","Damaged (1981)"],["Loved","My War (1984)"]],"Guitarist <b>Greg Ginn</b>'s band; <b>Henry Rollins</b> became its final, famous frontman."],
    badbrains:["Bad Brains",1982,"punk","Blistering, virtuosic hardcore revered across genres.",[],0,[["Essential","Bad Brains (1982)"],["Loved","I Against I (1986)"]]],
    minorthreat:["Minor Threat",1981,"punk","Fast, tight, principled hardcore.",["ramones","blackflag"],0,[["Essential","Complete Discography (comp.)"]],"Fronted by <b>Ian MacKaye</b>, who went on to form Fugazi and define hardcore's DIY ethic."],
    misfits:["Misfits",1982,"punk","Horror-punk that bridged into metal.",["ramones"],0,[["Best","Walk Among Us (1982)"],["Comp","Collection I"]],"Fronted by <b>Glenn Danzig</b> before Samhain and Danzig."],
    deadkennedys:["Dead Kennedys",1980,"punk","Fast, surfy, savagely political hardcore.",["stooges","ramones"],0,[["Essential","Fresh Fruit for Rotting Vegetables (1980)"]]],
    pereubu:["Pere Ubu",1978,"postpunk","Art-punk dread, weird and unsettling.",["stooges"],0,[["Essential","The Modern Dance (1978)"]]],
    cramps:["The Cramps",1980,"garage","Rockabilly through a horror movie - psychobilly's founders.",["linkwray","sonics"],0,[["Start","Songs the Lord Taught Us (1980)"],["Comp","Bad Music for Bad People"]]],
    birthday:["The Birthday Party",1981,"postpunk","Nick Cave's deranged, swampy early band.",["stooges"],0,[["Essential","Prayers on Fire (1981)"],["Loved","Junkyard (1982)"]],"Fronted by <b>Nick Cave</b> before his celebrated solo career with the Bad Seeds."],
    gunclub:["The Gun Club",1981,"garage","Swampy, twangy blues-punk played with real menace.",["cramps","stooges"],0,[["Best","Fire of Love (1981)"],["Loved","Miami (1982)"]]],
    rem:["R.E.M.",1983,"college","The jangly, murmured founders of college rock.",["byrds","bigstar","pattismith"],0,[["Start","Murmur (1983)"],["Best","Automatic for the People (1992)"],["Loved","Document (1987)"]]],
    smiths:["The Smiths",1984,"college","Chiming guitars and literate melancholy.",["byrds","nydolls"],0,[["Best","The Queen Is Dead (1986)"],["Start","The Smiths (1984)"],["Comp","Hatful of Hollow (1984)"]],"<b>Johnny Marr</b>'s guitar and <b>Morrissey</b>'s words; Marr later joined Modest Mouse."],
    husker:["Hüsker Dü",1984,"punk","Hardcore speed melting into gorgeous melody.",["ramones","blackflag"],0,[["Best","New Day Rising (1985)"],["Epic","Zen Arcade (1984)"],["Softer","Candy Apple Grey (1986)"]]],
    replacements:["The Replacements",1984,"college","Drunken punk that grew into heartfelt rock.",["bigstar","ramones"],0,[["Best","Let It Be (1984)"],["Loved","Pleased to Meet Me (1987)"]]],
    cheaptrick:["Cheap Trick",1978,"college","Power pop with hard-rock muscle and huge hooks.",["beatles","who"],0,[["Essential","At Budokan (1979)"],["Best","Heaven Tonight (1978)"]]],
    thecars:["The Cars",1978,"college","Sleek new-wave power pop.",["velvet","roxymusic"],0,[["Essential","The Cars (1978)"]],"Led by <b>Ric Ocasek</b>, later a sought-after producer (Weezer's Blue Album)."],
    violentfemmes:["Violent Femmes",1983,"college","Twitchy acoustic punk-folk.",["velvet"],0,[["Essential","Violent Femmes (1983)"]]],
    sonicyouth:["Sonic Youth",1988,"noise","The bridge between the avant-garde and alt-rock.",["velvet","stooges"],0,[["Best","Daydream Nation (1988)"],["Loved","Goo (1990)"],["Start","Sister (1987)"]]],
    pixies:["Pixies",1988,"indie","The loud-quiet-loud blueprint, and everyone's favorite influence.",["velvet","wire","husker","stooges"],0,[["Best","Doolittle (1989)"],["Raw","Surfer Rosa (1988)"],["Loved","Bossanova (1990)"]],"<b>Kim Deal</b> left to lead The Breeders; Black Francis went solo as Frank Black."],
    jamc:["The Jesus and Mary Chain",1985,"noise","Sweet pop buried under a wall of feedback.",["velvet","stooges","ramones"],0,[["Essential","Psychocandy (1985)"],["Loved","Darklands (1987)"]],"Early drummer <b>Bobby Gillespie</b> left to lead Primal Scream."],
    dinosaurjr:["Dinosaur Jr.",1987,"noise","Melody buried under enormous fuzz.",["stooges","husker"],0,[["Best","You're Living All Over Me (1987)"],["Loved","Bug (1988)"]],"Bassist <b>Lou Barlow</b> left to form Sebadoh and Folk Implosion."],
    meatpuppets:["Meat Puppets",1984,"indie","Punk that wandered into psychedelic country.",["blackflag"],0,[["Essential","Meat Puppets II (1984)"]]],
    cocteau:["Cocteau Twins",1984,"noise","Ethereal, effects-drenched dream pop.",["siouxsie"],0,[["Best","Heaven or Las Vegas (1990)"],["Loved","Treasure (1984)"]]],
    janesaddiction:["Jane's Addiction",1988,"indie","Art-metal-funk that lit the alt-rock explosion.",["ledzep","stooges"],0,[["Best","Nothing's Shocking (1988)"],["Loved","Ritual de lo Habitual (1990)"]],"Singer <b>Perry Farrell</b> founded Lollapalooza, the festival that mainstreamed alternative rock."],
    metallica:["Metallica",1986,"metal","Punk speed crashed into metal - the foundation of thrash.",["sabbath","deeppurple","motorhead","judaspriest"],0,[["Best","Master of Puppets (1986)"],["Loved","Ride the Lightning (1984)"],["Huge","Metallica (Black Album, 1991)"]]],
    slayer:["Slayer",1986,"metal","The fastest, most extreme of the thrash Big Four.",["sabbath","motorhead"],0,[["Essential","Reign in Blood (1986)"],["Loved","South of Heaven (1988)"]]],
    megadeth:["Megadeth",1986,"metal","The most technical of the thrash Big Four.",["sabbath","judaspriest","motorhead"],0,[["Best","Rust in Peace (1990)"],["Loved","Peace Sells... but Who's Buying? (1986)"]],"Founded by <b>Dave Mustaine</b> after he was fired from Metallica."],
    anthrax:["Anthrax",1987,"metal","The punk-influenced, most fun of the Big Four.",["sabbath","motorhead","ramones"],0,[["Best","Among the Living (1987)"]]],
    ironmaiden:["Iron Maiden",1982,"metal","The galloping heart of British heavy metal.",["deeppurple","sabbath","judaspriest"],0,[["Best","The Number of the Beast (1982)"],["Loved","Powerslave (1984)"]]],
    venom:["Venom",1982,"metal","Raw proto-black/thrash that named the genre.",["motorhead","sabbath"],0,[["Essential","Black Metal (1982)"]]],
    pantera:["Pantera",1992,"metal","Groove-metal heaviness that ruled the 90s.",["sabbath","metallica"],0,[["Best","Vulgar Display of Power (1992)"],["Loved","Cowboys from Hell (1990)"]]],
    death:["Death",1991,"metal","The pioneers of death metal.",["slayer","sabbath"],0,[["Best","Symbolic (1995)"],["Start","Leprosy (1988)"]],"The vision of <b>Chuck Schuldiner</b>, widely called the godfather of death metal."],
    mayhem:["Mayhem",1994,"metal","Notorious Norwegian black metal.",["venom","slayer"],0,[["Essential","De Mysteriis Dom Sathanas (1994)"]]],
    meshuggah:["Meshuggah",1998,"metal","Swedish pioneers of djent - polyrhythmic, syncopated riffing.",["metallica","sabbath"],0,[["Best","obZen (2008)"],["Start","Destroy Erase Improve (1995)"]]],
    mastodon:["Mastodon",2004,"metal","Progressive sludge metal with scope and groove.",["sabbath","melvins"],0,[["Best","Leviathan (2004)"],["Loved","Crack the Skye (2009)"]]],
    gojira:["Gojira",2005,"metal","French progressive/groove death metal, heavy and atmospheric.",["death","metallica"],0,[["Best","From Mars to Sirius (2005)"],["Loved","Magma (2016)"]]],
    lambofgod:["Lamb of God",2004,"metal","Ferocious American groove metal and metalcore.",["pantera","slayer"],0,[["Best","Ashes of the Wake (2004)"],["Loved","Sacrament (2006)"]]],
    opeth:["Opeth",2001,"metal","Prog-death that swings from brutal to beautiful.",["death","kingcrimson"],0,[["Best","Blackwater Park (2001)"],["Loved","Ghost Reveries (2005)"]]],
    converge:["Converge",2001,"metal","Chaotic, cathartic metalcore and mathcore.",["blackflag","slayer"],0,[["Essential","Jane Doe (2001)"]]],
    killswitch:["Killswitch Engage",2004,"metal","The melodic metalcore blueprint.",["ironmaiden","pantera"],0,[["Best","The End of Heartache (2004)"],["Loved","Alive or Just Breathing (2002)"]]],
    periphery:["Periphery",2010,"metal","Djent brought into the digital age.",["meshuggah","tool"],0,[["Best","Periphery II (2012)"],["Loved","Hail Stan (2019)"]]],
    codeorange:["Code Orange",2020,"metal","Industrial-tinged hardcore and metal, jarring and modern.",["korn","ministry"],0,[["Best","Underneath (2020)"],["Loved","Forever (2017)"]]],
    lornashore:["Lorna Shore",2022,"metal","Symphonic deathcore at monstrous scale.",["death","slayer"],0,[["Essential","Pain Remains (2022)"]]],
    spiritbox:["Spiritbox",2021,"metal","Modern metalcore with djent, ambience, and huge hooks.",["meshuggah","deftones"],0,[["Essential","Eternal Blue (2021)"],["New","Tsunami Sea (2025)"]]],
    knockedloose:["Knocked Loose",2024,"metal","Brutal, hardcore-fed metalcore that broke into the mainstream.",["pantera","blackflag"],0,[["Essential","You Won't Go Before You're Supposed To (2024)"],["Loved","A Different Shade of Blue (2019)"]]],
    sleeptoken:["Sleep Token",2023,"metal","Genre-melting, emotional modern metal - one of the biggest new acts.",["tool","deftones"],0,[["Best","Take Me Back to Eden (2023)"],["New","Even in Arcadia (2025)"]]],
    mbv:["My Bloody Valentine",1991,"noise","Guitars turned into vast oceans of blurred sound.",["jamc","velvet"],0,[["Essential","Loveless (1991)"],["Start","Isn't Anything (1988)"]]],
    slowdive:["Slowdive",1993,"noise","Warmer, dreamier shoegaze walls.",["mbv","thecure"],0,[["Best","Souvlaki (1993)"],["Loved","Slowdive (2017)"]]],
    ride:["Ride",1990,"noise","Propulsive, cascading shoegaze.",["mbv","jamc"],0,[["Essential","Nowhere (1990)"]]],
    swervedriver:["Swervedriver",1991,"noise","The heavier, driving end of shoegaze.",["mbv","dinosaurjr"],0,[["Essential","Raise (1991)"]]],
    slint:["Slint",1991,"noise","Quiet-then-loud tension that invented post-rock.",["sonicyouth"],0,[["Essential","Spiderland (1991)"]]],
    jesuslizard:["The Jesus Lizard",1991,"noise","Menacing, lurching noise rock.",["sonicyouth","birthday"],0,[["Best","Goat (1991)"],["Loved","Liar (1992)"]]],
    mogwai:["Mogwai",1997,"noise","Quiet-to-crushing instrumental post-rock.",["slint","sonicyouth"],0,[["Best","Young Team (1997)"],["Loved","Happy Songs for Happy People (2003)"]]],
    godspeed:["Godspeed You! Black Emperor",1998,"noise","Apocalyptic, cinematic post-rock.",["slint"],0,[["Essential","Lift Your Skinny Fists Like Antennas... (2000)"],["Start","F♯ A♯ ∞ (1997)"]]],
    explosions:["Explosions in the Sky",2003,"noise","Shimmering, emotional post-rock.",["slint","mogwai"],0,[["Essential","The Earth Is Not a Cold Dead Place (2003)"]]],
    melvins:["The Melvins",1991,"metal","Sludgy, slow, crushing - Cobain's heroes.",["sabbath","stooges","blackflag"],0,[["Best","Houdini (1993)"],["Loved","Bullhead (1991)"]],"<b>Buzz Osborne</b> mentored a young Kurt Cobain; drummer Dale Crover briefly played in Nirvana."],
    greenriver:["Green River",1986,"grunge","The proto-grunge band that split into Mudhoney and Pearl Jam.",["stooges","sabbath","blackflag"],0,[["Only","Rehab Doll (1988)"]],"Split down the middle: <b>Mark Arm</b> and Steve Turner formed Mudhoney, while Jeff Ament and Stone Gossard went on to Pearl Jam."],
    mudhoney:["Mudhoney",1988,"grunge","The snotty, punk end of early Seattle.",["stooges","sonics","greenriver"],0,[["Start","Superfuzz Bigmuff (1988)"],["Best","Mudhoney (1989)"]],"Formed by <b>Mark Arm</b> and Steve Turner out of Green River."],
    nirvana:["Nirvana",1991,"grunge","Took the Pixies' dynamics and conquered the planet.",["pixies","melvins","mudhoney","sabbath","sonicyouth","velvet"],0,[["Loved","Nevermind (1991)"],["Best","In Utero (1993)"],["Live","MTV Unplugged in New York (1994)"]],"<b>Kurt Cobain</b> — the reluctant voice of a generation. Drummer <b>Dave Grohl</b> went on to form Foo Fighters."],
    soundgarden:["Soundgarden",1994,"grunge","The heaviest, doomiest of the big grunge four.",["sabbath","stooges","ledzep"],0,[["Best","Superunknown (1994)"],["Loved","Badmotorfinger (1991)"]],"Fronted by <b>Chris Cornell</b>, later of Temple of the Dog and Audioslave."],
    pearljam:["Pearl Jam",1991,"grunge","The classic-rock, anthemic side of grunge.",["who","neilyoung","greenriver"],0,[["Start","Ten (1991)"],["Best","Vs. (1993)"]],"Guitarist Stone Gossard and bassist Jeff Ament came from Green River, via Mother Love Bone."],
    alicechains:["Alice in Chains",1992,"grunge","The darkest, sludgiest grunge, rooted in metal.",["sabbath","metallica"],0,[["Best","Dirt (1992)"],["Loved","Jar of Flies (1994)"]]],
    pumpkins:["The Smashing Pumpkins",1993,"grunge","Layered walls of guitar and huge dynamics.",["pixies","sabbath","mbv"],0,[["Best","Siamese Dream (1993)"],["Epic","Mellon Collie and the Infinite Sadness (1995)"]]],
    screamingtrees:["Screaming Trees",1992,"grunge","Melodic, psychedelic grunge.",["sabbath","doors"],0,[["Best","Dust (1996)"],["Loved","Sweet Oblivion (1992)"]],"Fronted by <b>Mark Lanegan</b>, later a QOTSA member and revered solo artist."],
    stp:["Stone Temple Pilots",1994,"grunge","Slick, muscular, radio-ruling grunge.",["sabbath","ledzep"],0,[["Best","Purple (1994)"],["Loved","Core (1992)"]],"Singer <b>Scott Weiland</b> later fronted Velvet Revolver with members of Guns N' Roses."],
    hole:["Hole",1994,"grunge","Raw, melodic, cathartic.",["pixies","sonicyouth"],0,[["Essential","Live Through This (1994)"],["Loved","Celebrity Skin (1998)"]],"Led by <b>Courtney Love</b>, Kurt Cobain's wife."],
    foofighters:["Foo Fighters",1997,"grunge","Grohl's post-Nirvana melodic hard rock.",["nirvana","husker"],0,[["Best","The Colour and the Shape (1997)"],["Loved","Wasting Light (2011)"]],"Started by <b>Dave Grohl</b>, Nirvana's drummer. Nate Mendel and William Goldsmith came from Sunny Day Real Estate."],
    sdre:["Sunny Day Real Estate",1994,"punk","The founders of melodic, emotional emo.",["fugazi","husker"],0,[["Essential","Diary (1994)"],["Loved","How It Feels to Be Something On (1998)"]],"Members Nate Mendel and William Goldsmith later joined Foo Fighters."],
    radiohead:["Radiohead",1997,"indie","Guitar band turned art-rock turned electronic.",["pixies","sonicyouth","velvet","can"],0,[["Best","OK Computer (1997)"],["Bold","Kid A (2000)"],["Loved","In Rainbows (2007)"]]],
    weezer:["Weezer",1994,"indie","The loud-quiet formula turned into power pop.",["pixies","bigstar"],0,[["Start","Weezer (Blue Album, 1994)"],["Cult","Pinkerton (1996)"]]],
    pavement:["Pavement",1994,"indie","The slacker, ironic heart of 90s indie.",["sonicyouth","bigstar","wire"],0,[["Best","Slanted and Enchanted (1992)"],["Loved","Crooked Rain, Crooked Rain (1994)"]]],
    stoneroses:["The Stone Roses",1989,"indie","Madchester jangle-dance that set up Britpop.",["byrds","bigstar"],0,[["Essential","The Stone Roses (1989)"]]],
    suede:["Suede",1993,"indie","Glam-tinged Britpop, Bowie's heirs.",["bowie","smiths"],0,[["Best","Dog Man Star (1994)"],["Start","Suede (1993)"]]],
    oasis:["Oasis",1995,"indie","Britpop swagger built on Beatles melody.",["beatles","pistols","stoneroses"],0,[["Loved","(What's the Story) Morning Glory? (1995)"],["Best","Definitely Maybe (1994)"]],"The warring <b>Gallagher brothers</b>, Liam and Noel."],
    blur:["Blur",1994,"indie","Arty, restless Britpop.",["kinks","pixies"],0,[["Best","Parklife (1994)"],["Loved","Blur (1997)"]],"<b>Damon Albarn</b> later founded the genre-hopping Gorillaz."],
    pulp:["Pulp",1995,"indie","Witty, novelistic Britpop.",["bowie"],0,[["Essential","Different Class (1995)"],["Loved","This Is Hardcore (1998)"]],"Fronted by the sharp-witted <b>Jarvis Cocker</b>."],
    wilco:["Wilco",2002,"indie","Alt-country turned fractured art-rock.",["bigstar","velvet"],0,[["Best","Yankee Hotel Foxtrot (2002)"],["Loved","Being There (1996)"]],"Grew out of Uncle Tupelo, the band that helped launch alt-country."],
    beck:["Beck",1996,"indie","Genre-hopping, sample-collage art-rock.",["velvet","pavement"],0,[["Best","Odelay (1996)"],["Loved","Sea Change (2002)"]]],
    modestmouse:["Modest Mouse",2004,"indie","Jittery, existential indie rock.",["pixies","pavement"],0,[["Best","The Lonesome Crowded West (1997)"],["Loved","The Moon & Antarctica (2000)"]],"<b>Johnny Marr</b> of The Smiths joined for 'We Were Dead Before the Ship Even Sank.'"],
    jimmyeatworld:["Jimmy Eat World",2001,"punk","The melodic breakthrough of emo.",["sdre","greenday"],0,[["Essential","Clarity (1999)"],["Loved","Bleed American (2001)"]]],
    strokes:["The Strokes",2001,"garage","Cool, back-to-basics garage that led the 2000s revival.",["velvet","television","stooges"],0,[["Start","Is This It (2001)"],["Loved","Room on Fire (2003)"]]],
    whitestripes:["The White Stripes",2003,"garage","Raw, bluesy garage-rock revival.",["stooges","gunclub"],0,[["Best","Elephant (2003)"],["Loved","White Blood Cells (2001)"]],"<b>Jack White</b> also leads The Raconteurs and a prolific solo career."],
    hives:["The Hives",2001,"garage","Sharp, high-energy Swedish garage-punk.",["stooges","sonics"],0,[["Start","Veni Vidi Vicious (2000)"]]],
    blackkeys:["The Black Keys",2010,"garage","Fuzzy, twangy, driving blues-rock revival.",["stooges","gunclub"],0,[["Best","Brothers (2010)"],["Loved","El Camino (2011)"]]],
    arctic:["Arctic Monkeys",2006,"garage","Spiky garage-rock that reinvents itself each record.",["strokes","stooges"],0,[["Start","Whatever People Say I Am... (2006)"],["Best","AM (2013)"],["Bold","Tranquility Base Hotel & Casino (2018)"]]],
    interpol:["Interpol",2002,"postpunk","Brooding post-punk revival.",["joydiv"],0,[["Essential","Turn on the Bright Lights (2002)"]]],
    franzferdinand:["Franz Ferdinand",2004,"indie","Angular, danceable post-punk revival.",["gangoffour","talkingheads"],0,[["Essential","Franz Ferdinand (2004)"]]],
    badreligion:["Bad Religion",1988,"punk","Melodic, brainy SoCal punk.",["ramones","blackflag"],0,[["Best","Suffer (1988)"],["Loved","No Control (1989)"]]],
    fugazi:["Fugazi",1989,"punk","Post-hardcore integrity and invention.",["minorthreat","blackflag"],0,[["Start","13 Songs (1989)"],["Best","Repeater (1990)"],["Loved","The Argument (2001)"]],"Co-led by <b>Ian MacKaye</b> (ex-Minor Threat) and Guy Picciotto (ex-Rites of Spring)."],
    greenday:["Green Day",1994,"punk","Pop-punk brats turned stadium rock-opera band.",["ramones","buzzcocks"],0,[["Loved","Dookie (1994)"],["Epic","American Idiot (2004)"]]],
    offspring:["The Offspring",1994,"punk","Melodic SoCal pop-punk breakthrough.",["ramones","badreligion"],0,[["Best","Smash (1994)"],["Underrated","Ixnay on the Hombre (1997)"]]],
    qotsa:["Queens of the Stone Age",2002,"indie","Heavy, hypnotic desert rock.",["sabbath","birthday"],0,[["Best","Songs for the Deaf (2002)"],["Loved","Rated R (2000)"]],"A revolving cast led by <b>Josh Homme</b>: Dave Grohl drummed on 'Songs for the Deaf,' and Screaming Trees' Mark Lanegan was a member."],
    deftones:["Deftones",2000,"metal","Atmospheric, shoegaze-tinged alternative metal.",["thecure","badbrains"],0,[["Best","White Pony (2000)"],["Loved","Around the Fur (1997)"]]],
    tool:["Tool",1996,"metal","Dark, complex, cerebral alt-metal.",["kingcrimson","sabbath"],0,[["Best","Ænima (1996)"],["Loved","Lateralus (2001)"]]],
    rage:["Rage Against the Machine",1992,"metal","Rap-metal fury and political fire.",["blackflag","sabbath"],0,[["Essential","Rage Against the Machine (1992)"],["Loved","Evil Empire (1996)"]],"Guitarist <b>Tom Morello</b> and the rhythm section later backed Chris Cornell in Audioslave."],
    korn:["Korn",1994,"metal","The founders of nu-metal - downtuned anguish.",["sabbath","pantera"],0,[["Start","Korn (1994)"],["Best","Follow the Leader (1998)"]]],
    systemofadown:["System of a Down",2001,"metal","Frenetic, theatrical alt-metal.",["sabbath","deadkennedys"],0,[["Essential","Toxicity (2001)"]]],
    linkinpark:["Linkin Park",2001,"metal","Nu-metal fused with electronics and huge hooks.",["korn","deftones"],0,[["Essential","Hybrid Theory (2000)"],["Loved","Meteora (2003)"]]],
    slipknot:["Slipknot",2001,"metal","Masked, brutal, maximal nu-metal.",["korn","sabbath"],0,[["Best","Iowa (2001)"],["Start","Slipknot (1999)"]]],
    rhcp:["Red Hot Chili Peppers",1999,"indie","Funk-rock energy turned stadium-huge.",["gangoffour","sabbath"],0,[["Best","Blood Sugar Sex Magik (1991)"],["Loved","Californication (1999)"]]],
    muse:["Muse",2003,"indie","Grandiose, prog-tinged arena rock.",["radiohead","queen"],0,[["Best","Origin of Symmetry (2001)"],["Loved","Absolution (2003)"]]],
    kingsofleon:["Kings of Leon",2008,"indie","Southern-tinged garage rock gone stadium.",["strokes","pixies"],0,[["Loved","Only by the Night (2008)"],["Best","Aha Shake Heartbreak (2004)"]]],
    coldplay:["Coldplay",2002,"indie","Anthemic, melodic stadium alt-rock.",["radiohead"],0,[["Best","A Rush of Blood to the Head (2002)"],["Start","Parachutes (2000)"]]],
    arcadefire:["Arcade Fire",2005,"indie","Sweeping, communal indie rock.",["talkingheads","bowie"],0,[["Essential","Funeral (2004)"],["Best","The Suburbs (2010)"]]],
    thenational:["The National",2007,"indie","Brooding, literate indie rock.",["joydiv","smiths"],0,[["Best","Boxer (2007)"],["Loved","High Violet (2010)"]]],
    vampireweekend:["Vampire Weekend",2008,"indie","Bright, preppy, Afropop-tinged indie.",["talkingheads","pixies"],0,[["Best","Modern Vampires of the City (2013)"],["Start","Vampire Weekend (2008)"]]],
    lcd:["LCD Soundsystem",2005,"postpunk","Dance-punk that revived post-punk grooves.",["talkingheads","gangoffour"],0,[["Best","Sound of Silver (2007)"],["Loved","This Is Happening (2010)"]],"The project of <b>James Murphy</b>, co-founder of DFA Records."],
    blocparty:["Bloc Party",2005,"postpunk","Jittery, danceable post-punk revival.",["gangoffour","joydiv"],0,[["Essential","Silent Alarm (2005)"]]],
    mcr:["My Chemical Romance",2006,"punk","Theatrical emo at its mainstream peak.",["misfits","greenday"],0,[["Best","The Black Parade (2006)"],["Loved","Three Cheers for Sweet Revenge (2004)"]]],
    paramore:["Paramore",2008,"punk","Hook-driven pop-punk and emo.",["greenday","husker"],0,[["Best","After Laughter (2017)"],["Loved","Riot! (2007)"]],"Fronted by <b>Hayley Williams</b>."],
    tame:["Tame Impala",2012,"indie","Psychedelic rock reborn for the modern era.",["beatles","pinkfloyd","beachboys"],0,[["Best","Currents (2015)"],["Loved","Lonerism (2012)"]],"Essentially the one-man studio project of <b>Kevin Parker</b>."],
    wolfalice:["Wolf Alice",2015,"indie","Dreamy-to-crushing modern alt-rock.",["pixies","mbv"],0,[["Best","Visions of a Life (2017)"],["Loved","Blue Weekend (2021)"]]],
    fontaines:["Fontaines D.C.",2019,"indie","Brooding, literary modern post-punk.",["joydiv","strokes"],0,[["Best","Skinty Fia (2022)"],["Start","Dogrel (2019)"],["New","Romance (2024)"]]],
    idles:["IDLES",2018,"punk","Modern post-punk fury and catharsis.",["gangoffour","blackflag"],0,[["Best","Joy as an Act of Resistance (2018)"],["Loved","Brutalism (2017)"]]],
    audioslave:["Audioslave",2002,"grunge","Chris Cornell's voice over Rage Against the Machine's rhythm section.",["soundgarden","rage"],0,[["Best","Audioslave (2002)"],["Loved","Out of Exile (2005)"]],"Formed by <b>Chris Cornell</b> (Soundgarden) with Tom Morello, Tim Commerford and Brad Wilk — the three instrumentalists of Rage Against the Machine."],
    templeofthedog:["Temple of the Dog",1991,"grunge","A one-off tribute that united Seattle's two biggest bands-in-waiting.",["soundgarden"],0,[["Only","Temple of the Dog (1991)"]],"Led by <b>Chris Cornell</b> as a tribute to Andrew Wood, with Eddie Vedder, Stone Gossard, Jeff Ament and Mike McCready — soon to be Pearl Jam."],
    blackmidi:["black midi",2019,"postpunk","Frenetic, virtuosic, genre-shredding post-punk.",["kingcrimson","thefall"],1,[["Best","Cavalcade (2021)"],["Start","Schlagenheim (2019)"]]],
    bcnr:["Black Country, New Road",2021,"indie","Chamber-rock ambition and emotional heft.",["slint","talkingheads"],1,[["Essential","Ants from Up There (2022)"]]],
    squid:["Squid",2021,"postpunk","Krautrock-driven, restless modern post-punk.",["thefall","can"],1,[["Essential","Bright Green Field (2021)"]]],
    shame:["Shame",2018,"postpunk","Wiry, cathartic South London post-punk.",["gangoffour","thefall"],1,[["Best","Drunk Tank Pink (2021)"],["Start","Songs of Praise (2018)"]]],
    wetleg:["Wet Leg",2021,"indie","Deadpan, hooky, viral indie rock.",["pixies"],1,[["Essential","Wet Leg (2022)"]]],
    tagabow:["They Are Gutting a Body of Water",2022,"noise","Emotional, glitchy American shoegaze.",["mbv"],1,[["Start","S (2021)"],["Loved","Lucky Styles (2023)"]]],
    wisp:["Wisp",2024,"noise","Viral new-wave shoegaze.",["mbv","slowdive"],1,[["So far","Pandora (2025)"]]],
    julie:["Julie",2024,"noise","Heavy, melodic modern shoegaze.",["mbv","hole"],1,[["So far","my anti-aircraft friend (2024)"]]],
    glare:["Glare",2024,"noise","Heavy, hardcore-tinged modern shoegaze.",["mbv","deftones"],1,[["So far","Sunset Funeral (2025)"]]],
    mjlenderman:["MJ Lenderman",2022,"indie","Ragged, funny, Neil Young-style alt-country.",["neilyoung","pavement"],1,[["Essential","Manning Fireworks (2024)"],["Loved","Boat Songs (2022)"]],"Also plays guitar in Wednesday."],
    wednesday:["Wednesday",2023,"indie","Loud, distorted, Southern-tinged alt-rock.",["dinosaurjr","neilyoung"],1,[["Essential","Rat Saw God (2023)"]],"Guitarist <b>MJ Lenderman</b> is a member alongside his acclaimed solo career."],
    alexg:["Alex G",2019,"indie","Lo-fi, off-kilter, deeply beloved indie.",["pavement","modestmouse"],1,[["Best","Rocket (2017)"],["Loved","House of Sugar (2019)"],["New","God Save the Animals (2022)"]]],
    bigthief:["Big Thief",2019,"indie","Raw, dynamic, emotionally direct indie folk-rock.",["neilyoung","velvet"],1,[["Best","Dragon New Warm Mountain I Believe in You (2022)"],["Loved","U.F.O.F. (2019)"]],"Fronted by <b>Adrianne Lenker</b>, also a revered solo artist."],
    snailmail:["Snail Mail",2018,"indie","Melodic, aching, 90s-alt indie.",["pavement","smiths"],1,[["Essential","Lush (2018)"],["Loved","Valentine (2021)"]]],
    soccermommy:["Soccer Mommy",2018,"indie","90s-alt melody with modern melancholy.",["smiths","pavement"],1,[["Essential","Clean (2018)"],["Loved","color theory (2020)"]]],
    geese:["Geese",2021,"indie","Fearless, post-genre modern rock.",["talkingheads","thefall"],1,[["Best","3D Country (2023)"],["Start","Projector (2021)"]]],
    baritalia:["Bar Italia",2023,"indie","Cool, seductive London-underground guitar rock.",["velvet","thecure"],1,[["Essential","Tracey Denim (2023)"],["Loved","The Twits (2023)"]]],
    turnstile:["Turnstile",2021,"punk","Hardcore that swallowed melody whole.",["badbrains","minorthreat"],1,[["Essential","Glow On (2021)"],["Loved","Time & Space (2018)"]]],
    militariegun:["Militarie Gun",2023,"punk","Punchy, melodic, cathartic post-hardcore.",["husker","fugazi"],1,[["Essential","Life Under the Gun (2023)"]]],
    anxious:["Anxious",2022,"punk","Bright, urgent melodic hardcore and emo.",["sdre","turnstile"],1,[["Essential","Little Green House (2022)"],["New","Bambi (2024)"]]],
    chatpile:["Chat Pile",2022,"noise","Bleak, punishing modern noise-sludge.",["jesuslizard","melvins"],1,[["Essential","God's Country (2022)"]]],
    faithnomore:["Faith No More",1989,"metal","Funk, metal, and art-rock crashed together - a nu-metal precursor.",["blackflag","sabbath"],0,[["Best","Angel Dust (1992)"],["Loved","The Real Thing (1989)"]]],
    primus:["Primus",1991,"metal","Bass-driven funk-metal weirdness, virtuosic and cartoonish.",["rush","blackflag"],0,[["Best","Sailing the Seas of Cheese (1991)"],["Loved","Frizzle Fry (1990)"]]],
    rammstein:["Rammstein",1998,"metal","Thunderous German industrial metal - Neue Deutsche Härte.",["ministry","sabbath"],0,[["Best","Mutter (2001)"],["Loved","Sehnsucht (1997)"]]],
    ghost:["Ghost",2013,"metal","Theatrical occult rock - metal riffs with pop and arena sheen.",["sabbath","queen"],0,[["Best","Meliora (2015)"],["Loved","Prequelle (2018)"]]],
    deafheaven:["Deafheaven",2013,"metal","Blackgaze - black metal fused with shoegaze beauty.",["mayhem","mbv"],0,[["Essential","Sunbather (2013)"]]],
    badseeds:["Nick Cave & the Bad Seeds",1984,"postpunk","Grand, gothic murder-ballad art-rock.",["birthday","velvet"],0,[["Best","The Boatman's Call (1997)"],["Dark","Murder Ballads (1996)"],["Loved","Push the Sky Away (2013)"]],"Led by <b>Nick Cave</b>, continuing from his early band The Birthday Party."],
    pjharvey:["PJ Harvey",1992,"indie","Fierce, shape-shifting art-rock - blues-punk to stark balladry.",["pattismith","stooges"],0,[["Best","Rid of Me (1993)"],["Loved","Stories from the City, Stories from the Sea (2000)"],["Bold","Let England Shake (2011)"]]],
    flaminglips:["The Flaming Lips",1993,"indie","Psychedelic art-rock, from noisy to symphonic and strange.",["pinkfloyd","velvet"],0,[["Best","The Soft Bulletin (1999)"],["Loved","Yoshimi Battles the Pink Robots (2002)"]]],
    yeahyeahyeahs:["Yeah Yeah Yeahs",2003,"garage","Art-punk with Karen O's ferocity and jagged hooks.",["stooges","pattismith"],0,[["Best","Fever to Tell (2003)"],["Loved","It's Blitz! (2009)"]]],
    tvotr:["TV on the Radio",2006,"indie","Dense, soulful art-rock - horns, falsetto, and noise.",["talkingheads","pixies"],0,[["Best","Return to Cookie Mountain (2006)"],["Loved","Dear Science (2008)"]]],
    sigurros:["Sigur Rós",2000,"noise","Glacial, ethereal post-rock sung in a made-up language.",["slint","mogwai"],0,[["Best","Ágætis byrjun (1999)"],["Loved","( ) (2002)"]]],
    swans:["Swans",1987,"noise","Punishing, transcendent no-wave noise-rock.",["velvet","stooges"],0,[["Best","Soundtracks for the Blind (1996)"],["Modern","To Be Kind (2014)"]]],
    kinggizzard:["King Gizzard & the Lizard Wizard",2014,"garage","Prolific, restless psych that swerves from boogie to thrash metal.",["beatles","sabbath"],0,[["Start","Nonagon Infinity (2016)"],["Metal","Infest the Rats' Nest (2019)"],["Loved","Flying Microtonal Banana (2017)"]]],
    gorillaz:["Gorillaz",2001,"indie","A genre-melting virtual band - rock, hip-hop, electronic, and pop.",["blur","talkingheads"],0,[["Best","Demon Days (2005)"],["Loved","Plastic Beach (2010)"]],"The virtual-band project of <b>Damon Albarn</b> of Blur."],
    alabamashakes:["Alabama Shakes",2012,"southern","Raw, soulful blues-rock powered by Brittany Howard's voice.",["ccr","stones"],0,[["Best","Sound & Color (2015)"],["Start","Boys & Girls (2012)"]]],
    marsvolta:["The Mars Volta",2003,"indie","Frenetic prog fused with post-hardcore and Latin fire.",["kingcrimson","fugazi"],0,[["Best","De-Loused in the Comatorium (2003)"],["Loved","Frances the Mute (2005)"]]],
    robertjohnson:["Robert Johnson",1936,"roots","The mythic Delta blues wellspring behind all of it.",[],0,[["Essential","King of the Delta Blues Singers (comp.)"]]],
    everly:["The Everly Brothers",1957,"roots","Close-harmony pop that shaped the Beatles and the Byrds.",[],0,[["Comp","Cadence Classics (best-of)"]]],
    love:["Love",1967,"sixties","Arthur Lee's baroque psychedelic cult classic.",[],0,[["Essential","Forever Changes (1967)"]]],
    elevators:["The 13th Floor Elevators",1966,"garage","Pioneering psychedelic garage rock.",[],0,[["Essential","The Psychedelic Sounds of the 13th Floor Elevators (1966)"]]],
    beefheart:["Captain Beefheart",1969,"garage","Warped avant-blues that rewired rock's rules.",["howlinwolf"],0,[["Essential","Trout Mask Replica (1969)"],["Start","Safe as Milk (1967)"]]],
    eno:["Brian Eno",1973,"experimental","Ambient pioneer and the era's most influential producer.",["velvet","roxymusic"],0,[["Best","Another Green World (1975)"],["Ambient","Music for Airports (1978)"]]],
    suicide:["Suicide",1977,"experimental","Menacing electronic proto-punk - drum machine and scream.",["velvet","stooges"],0,[["Essential","Suicide (1977)"]]],
    throbbinggristle:["Throbbing Gristle",1977,"experimental","The confrontational inventors of industrial music.",[],0,[["Essential","20 Jazz Funk Greats (1979)"]]],
    killingjoke:["Killing Joke",1980,"postpunk","Pounding, apocalyptic post-punk that fed metal and grunge.",["pil","sabbath"],0,[["Best","Killing Joke (1980)"],["Loved","Night Time (1985)"]]],
    depechemode:["Depeche Mode",1981,"postpunk","Synth-pop turned dark, huge, and hugely influential.",["kraftwerk"],0,[["Best","Violator (1990)"],["Loved","Music for the Masses (1987)"]]],
    sparks:["Sparks",1974,"postpunk","Arch, theatrical art-pop that shaped new wave.",["beatles"],0,[["Best","Kimono My House (1974)"]]],
    missionofburma:["Mission of Burma",1981,"postpunk","Explosive art-punk that pointed toward alt-rock.",["wire","stooges"],0,[["Essential","Vs. (1982)"]]],
    spacemen3:["Spacemen 3",1986,"noise","Drone, drug-haze, and neo-psych that fed shoegaze.",["stooges","velvet"],0,[["Best","The Perfect Prescription (1987)"]]],
    bigblack:["Big Black",1986,"noise","Abrasive, mechanized noise-rock.",["stooges","gangoffour"],0,[["Essential","Atomizer (1986)"],["Loved","Songs About Fucking (1987)"]],"Fronted by <b>Steve Albini</b>, later the engineer behind the Pixies' Surfer Rosa and Nirvana's In Utero."],
    kyuss:["Kyuss",1992,"metal","The desert and stoner-rock pioneers.",["sabbath","blackflag"],0,[["Best","Welcome to Sky Valley (1994)"],["Loved","Blues for the Red Sun (1992)"]],"<b>Josh Homme</b>'s band before Queens of the Stone Age."],
    bathory:["Bathory",1987,"metal","Blueprinted Scandinavian black metal, then Viking metal.",["venom","sabbath"],0,[["Best","Under the Sign of the Black Mark (1987)"],["Epic","Hammerheart (1990)"]]],
    napalmdeath:["Napalm Death",1988,"metal","Grindcore - hardcore taken to a brutal extreme.",["blackflag","sabbath"],0,[["Essential","Scum (1987)"]]],
    sepultura:["Sepultura",1991,"metal","Brazilian thrash that grew into tribal groove metal.",["slayer","sabbath"],0,[["Best","Roots (1996)"],["Loved","Chaos A.D. (1993)"]]],
    neurosis:["Neurosis",1996,"metal","Vast, crushing atmosphere - the birth of post-metal.",["melvins","sabbath"],0,[["Best","Through Silver in Blood (1996)"],["Loved","Times of Grace (1999)"]]],
    refused:["Refused",1998,"punk","Explosive, arty post-hardcore that reshaped the genre.",["minorthreat","fugazi"],0,[["Essential","The Shape of Punk to Come (1998)"]]],
    atdi:["At the Drive-In",2000,"punk","Frantic, poetic post-hardcore.",["fugazi","blackflag"],0,[["Essential","Relationship of Command (2000)"]],"Splintered into The Mars Volta and Sparta."],
    descendents:["Descendents",1982,"punk","Fast, melodic, nerdy - a pop-punk and emo cornerstone.",["ramones","blackflag"],0,[["Best","Milo Goes to College (1982)"],["Loved","Everything Sucks (1996)"]]],
    ritesofspring:["Rites of Spring",1985,"punk","Hardcore turned confessional - the first emo band.",["minorthreat"],0,[["Essential","Rites of Spring (1985)"]],"Guy Picciotto's band, who went on to co-found Fugazi."],
    gbv:["Guided by Voices",1994,"indie","Prolific lo-fi indie built on British-Invasion hooks.",["beatles","wire"],0,[["Best","Bee Thousand (1994)"],["Loved","Alien Lanes (1995)"]]],
    nmh:["Neutral Milk Hotel",1998,"indie","Fuzzy, surreal, deeply beloved indie folk.",["velvet"],0,[["Essential","In the Aeroplane Over the Sea (1998)"]]],
    rosettatharpe:["Sister Rosetta Tharpe",1944,"roots","Gospel guitar firebrand who prefigured rock and roll.",[],0,[["Comp","The Original Soul Sister"]]],
    johnleehooker:["John Lee Hooker",1949,"roots","Hypnotic, boogie-driven Delta-to-Detroit blues.",[],0,[["Comp","The Ultimate Collection"]]],
    bbking:["B.B. King",1951,"roots","The most influential electric blues guitarist.",[],0,[["Live","Live at the Regal (1965)"]]],
    fatsdomino:["Fats Domino",1950,"roots","Rolling New Orleans R&B and rock and roll.",[],0,[["Comp","Greatest Hits"]]],
    jerryleelewis:["Jerry Lee Lewis",1957,"roots","Wild piano-pounding rockabilly.",[],0,[["Comp","18 Original Sun Greatest Hits"]]],
    eddiecochran:["Eddie Cochran",1958,"roots","Sharp, riff-driven rockabilly.",[],0,[["Comp","Somethin' Else"]]],
    theanimals:["The Animals",1964,"sixties","Gritty British R&B.",["stones","muddywaters"],0,[["Comp","The Best of The Animals"]]],
    thezombies:["The Zombies",1965,"sixties","Baroque, jazzy 60s pop.",["beatles"],0,[["Best","Odessey and Oracle (1968)"]]],
    smallfaces:["Small Faces",1966,"sixties","Mod R&B and psychedelia.",["kinks","who"],0,[["Best","Ogdens' Nut Gone Flake (1968)"]]],
    them:["Them",1965,"sixties","Van Morrison's raw R&B garage.",["stones"],0,[["Essential","The Angry Young Them (1965)"]]],
    buffalospringfield:["Buffalo Springfield",1967,"sixties","Folk-rock that spawned CSNY and Neil Young.",["byrds","dylan"],0,[["Best","Buffalo Springfield Again (1967)"]]],
    jeffersonairplane:["Jefferson Airplane",1967,"sixties","Psychedelic San Francisco pioneers.",["byrds"],0,[["Best","Surrealistic Pillow (1967)"]]],
    csny:["Crosby, Stills, Nash & Young",1969,"sixties","Harmony-rich folk-rock supergroup.",["byrds","buffalospringfield"],0,[["Best","Deja Vu (1970)"]]],
    steppenwolf:["Steppenwolf",1968,"sixties","Heavy proto-metal biker rock.",["stones"],0,[["Hit","Steppenwolf (1968)"]]],
    theband:["The Band",1968,"southern","Rustic Americana that reshaped roots rock.",["dylan"],0,[["Best","The Band (1969)"]]],
    procolharum:["Procol Harum",1967,"prog","Baroque, organ-driven proto-prog.",["beatles"],0,[["Best","A Salty Dog (1969)"]]],
    zztop:["ZZ Top",1971,"southern","Texan blues-boogie trio.",["stones","muddywaters"],0,[["Best","Tres Hombres (1973)"],["Hit","Eliminator (1983)"]]],
    littlefeat:["Little Feat",1973,"southern","Slippery, funky Southern roots-rock.",[],0,[["Best","Dixie Chicken (1973)"]]],
    gramparsons:["Gram Parsons",1973,"southern","The architect of country-rock.",["byrds"],0,[["Best","Grievous Angel (1974)"]]],
    uncletupelo:["Uncle Tupelo",1990,"southern","Launched alt-country.",["neilyoung","husker"],0,[["Essential","No Depression (1990)"]]],
    drivebytruckers:["Drive-By Truckers",2001,"southern","Novelistic Southern rock.",["neilyoung","lynyrdskynyrd"],0,[["Best","Southern Rock Opera (2001)"]]],
    jasonisbell:["Jason Isbell",2013,"southern","Literate modern Americana.",["neilyoung","springsteen"],0,[["Best","Southeastern (2013)"]]],
    lucindawilliams:["Lucinda Williams",1998,"southern","Raw, poetic alt-country.",["neilyoung"],0,[["Best","Car Wheels on a Gravel Road (1998)"]]],
    blueoystercult:["Blue Oyster Cult",1972,"hardrock","Cerebral, riffy hard rock.",["sabbath"],0,[["Best","Agents of Fortune (1976)"]]],
    bluecheer:["Blue Cheer",1968,"hardrock","Deafening proto-metal.",["hendrix"],0,[["Essential","Vincebus Eruptum (1968)"]]],
    badcompany:["Bad Company",1974,"hardrock","Bluesy, anthemic hard rock.",["ledzep"],0,[["Best","Bad Company (1974)"]]],
    ufo:["UFO",1974,"hardrock","Twin-guitar British hard rock.",["deeppurple"],0,[["Best","Strangers in the Night (1979)"]]],
    vanhalen:["Van Halen",1978,"hardrock","Guitar-hero party hard rock.",["cream","kinks"],0,[["Best","Van Halen (1978)"],["Hit","1984 (1984)"]]],
    mottthehoople:["Mott the Hoople",1972,"glam","Bowie-boosted glam rockers.",["stones","bowie"],0,[["Best","All the Young Dudes (1972)"]]],
    kiss:["KISS",1974,"glam","Stadium spectacle hard rock.",["nydolls","stooges"],0,[["Best","Destroyer (1976)"],["Live","Alive! (1975)"]]],
    hawkwind:["Hawkwind",1972,"prog","Space-rock drone.",["pinkfloyd"],0,[["Best","Space Ritual (1973)"]],"Lemmy played bass here before founding Motorhead."],
    jethrotull:["Jethro Tull",1971,"prog","Flute-driven folk-prog.",[],0,[["Best","Aqualung (1971)"]]],
    elp:["Emerson, Lake & Palmer",1971,"prog","Bombastic keyboard prog.",["kingcrimson"],0,[["Best","Brain Salad Surgery (1973)"]]],
    softmachine:["Soft Machine",1970,"prog","Jazzy Canterbury prog.",[],0,[["Best","Third (1970)"]]],
    rainbow:["Rainbow",1976,"metal","Blackmore's neoclassical hard rock.",["deeppurple"],0,[["Best","Rising (1976)"]]],
    scorpions:["Scorpions",1979,"metal","German melodic hard rock and metal.",["deeppurple","judaspriest"],0,[["Best","Blackout (1982)"]]],
    dio:["Dio",1983,"metal","Ronnie James Dio's fantasy metal.",["sabbath","rainbow"],0,[["Best","Holy Diver (1983)"]]],
    mercyfulfate:["Mercyful Fate",1983,"metal","Theatrical proto-black metal.",["judaspriest","sabbath"],0,[["Best","Melissa (1983)"]]],
    diamondhead:["Diamond Head",1980,"metal","NWOBHM band Metallica revered.",["judaspriest","sabbath"],0,[["Essential","Lightning to the Nations (1980)"]],"Metallica's covers revived their reputation."],
    saxon:["Saxon",1980,"metal","NWOBHM workhorses.",["judaspriest"],0,[["Best","Wheels of Steel (1980)"]]],
    candlemass:["Candlemass",1986,"metal","Epic doom metal.",["sabbath"],0,[["Essential","Epicus Doomicus Metallicus (1986)"]]],
    electricwizard:["Electric Wizard",2000,"metal","Crushing stoner-doom.",["sabbath","sleep"],0,[["Best","Dopethrone (2000)"]]],
    highonfire:["High on Fire",2002,"metal","Punishing sludge-metal.",["sleep","motorhead"],0,[["Best","Blessed Black Wings (2005)"]]],
    testament:["Testament",1987,"metal","Bay Area thrash mainstays.",["metallica","slayer"],0,[["Best","The Legacy (1987)"]]],
    exodus:["Exodus",1985,"metal","Ferocious Bay Area thrash.",["metallica","slayer"],0,[["Best","Bonded by Blood (1985)"]],"An early home of Metallica's Kirk Hammett."],
    kreator:["Kreator",1986,"metal","German thrash leaders.",["slayer","venom"],0,[["Best","Pleasure to Kill (1986)"]]],
    overkill:["Overkill",1985,"metal","Relentless East Coast thrash.",["motorhead","slayer"],0,[["Best","The Years of Decay (1989)"]]],
    morbidangel:["Morbid Angel",1989,"metal","Death-metal titans.",["slayer","death"],0,[["Best","Altars of Madness (1989)"]]],
    cannibalcorpse:["Cannibal Corpse",1991,"metal","Brutal death metal.",["slayer","death"],0,[["Best","Tomb of the Mutilated (1992)"]]],
    atthegates:["At the Gates",1995,"metal","Melodic Swedish death metal.",["death","slayer"],0,[["Essential","Slaughter of the Soul (1995)"]]],
    emperor:["Emperor",1994,"metal","Symphonic Norwegian black metal.",["mayhem","bathory"],0,[["Best","In the Nightside Eclipse (1994)"]]],
    baroness:["Baroness",2007,"metal","Melodic, colorful sludge-prog.",["mastodon","neurosis"],0,[["Best","Red Album (2007)"]]],
    trivium:["Trivium",2005,"metal","Melodic metalcore and thrash.",["metallica","killswitch"],0,[["Best","Ascendancy (2005)"]]],
    dreamtheater:["Dream Theater",1992,"metal","Virtuosic prog metal.",["rush","metallica"],0,[["Best","Images and Words (1992)"]]],
    thestranglers:["The Stranglers",1977,"punk","Keyboard-driven punk and new wave.",["doors","pistols"],0,[["Best","Rattus Norvegicus (1977)"]]],
    stifflittlefingers:["Stiff Little Fingers",1979,"punk","Belfast political punk.",["clash"],0,[["Best","Inflammable Material (1979)"]]],
    theundertones:["The Undertones",1979,"punk","Buzzy Irish pop-punk.",["ramones","buzzcocks"],0,[["Best","The Undertones (1979)"]]],
    thesaints:["The Saints",1977,"punk","Australian proto-punk.",["stooges"],0,[["Essential","(I'm) Stranded (1977)"]]],
    x:["X",1980,"punk","Poetic LA punk.",["ramones","doors"],0,[["Best","Los Angeles (1980)"]]],
    thegerms:["The Germs",1979,"punk","Chaotic LA hardcore.",["stooges","ramones"],0,[["Essential","(GI) (1979)"]]],
    circlejerks:["Circle Jerks",1980,"punk","Fast, funny LA hardcore.",["blackflag"],0,[["Best","Group Sex (1980)"]]],
    suicidaltendencies:["Suicidal Tendencies",1983,"punk","Crossover thrash-hardcore.",["blackflag","slayer"],0,[["Best","Suicidal Tendencies (1983)"]]],
    cromags:["Cro-Mags",1986,"punk","NYHC crossover.",["badbrains","motorhead"],0,[["Essential","The Age of Quarrel (1986)"]]],
    gorillabiscuits:["Gorilla Biscuits",1989,"punk","Melodic NYHC youth-crew.",["minorthreat"],0,[["Essential","Start Today (1989)"]]],
    operationivy:["Operation Ivy",1989,"punk","Ska-punk that birthed Rancid.",["clash","minorthreat"],0,[["Essential","Energy (1989)"]]],
    rancid:["Rancid",1994,"punk","Clash-worshipping street punk.",["clash","operationivy"],0,[["Best","...And Out Come the Wolves (1995)"]]],
    nofx:["NOFX",1994,"punk","Snotty melodic skate-punk.",["badreligion","ramones"],0,[["Best","Punk in Drublic (1994)"]]],
    quicksand:["Quicksand",1993,"punk","Heavy, groovy post-hardcore.",["fugazi","badbrains"],0,[["Essential","Slip (1993)"]]],
    jawbreaker:["Jawbreaker",1994,"punk","Gravelly, literate emo-punk.",["husker","fugazi"],0,[["Best","24 Hour Revenge Therapy (1994)"]]],
    jawbox:["Jawbox",1994,"punk","Angular DC post-hardcore.",["fugazi"],0,[["Best","For Your Own Special Sweetheart (1994)"]]],
    capnjazz:["Cap'n Jazz",1995,"punk","Manic Midwest-emo originators.",["sdre"],0,[["Comp","Analphabetapolothology"]]],
    thegetupkids:["The Get Up Kids",1999,"punk","Melodic Midwest emo.",["sdre","jawbreaker"],0,[["Best","Something to Write Home About (1999)"]]],
    thepromisering:["The Promise Ring",1997,"punk","Bright, catchy emo.",["capnjazz","sdre"],0,[["Best","Nothing Feels Good (1997)"]]],
    mineral:["Mineral",1997,"punk","Yearning, dynamic emo.",["sdre"],0,[["Best","The Power of Failing (1997)"]]],
    brandnew:["Brand New",2003,"punk","Ambitious, dark emo.",["sdre","jimmyeatworld"],0,[["Best","Deja Entendu (2003)"],["Loved","The Devil and God Are Raging Inside Me (2006)"]]],
    thursday:["Thursday",2001,"punk","Post-hardcore and screamo crossover.",["fugazi","sdre"],0,[["Best","Full Collapse (2001)"]]],
    toucheamore:["Touche Amore",2011,"punk","Cathartic modern post-hardcore.",["fugazi","refused"],0,[["Best","Stage Four (2016)"]]],
    titlefight:["Title Fight",2012,"punk","Punk-to-shoegaze emo.",["sdre","husker"],0,[["Best","Floral Green (2012)"]]],
    magazine:["Magazine",1978,"postpunk","Cerebral post-punk.",["pistols","buzzcocks"],0,[["Best","Real Life (1978)"]],"Founded by Buzzcocks' Howard Devoto."],
    sistersofmercy:["The Sisters of Mercy",1985,"postpunk","Drum-machine goth rock.",["joydiv","bauhaus"],0,[["Best","Floodland (1987)"]]],
    thechameleons:["The Chameleons",1983,"postpunk","Atmospheric, guitar-rich post-punk.",["joydiv","echobunnymen"],0,[["Best","Script of the Bridge (1983)"]]],
    theslits:["The Slits",1979,"postpunk","Dubby feminist post-punk.",["pistols"],0,[["Essential","Cut (1979)"]]],
    xtc:["XTC",1979,"postpunk","Clever, tuneful new wave.",["beatles","kinks"],0,[["Best","Skylarking (1986)"]]],
    thepretenders:["The Pretenders",1980,"postpunk","Tough, tuneful new-wave rock.",["kinks"],0,[["Best","Pretenders (1980)"]]],
    elviscostello:["Elvis Costello",1977,"postpunk","Sharp, literate new-wave songcraft.",["beatles","dylan"],0,[["Best","This Year's Model (1978)"]]],
    garynuman:["Gary Numan",1979,"postpunk","Cold synth-rock pioneer.",["kraftwerk","bowie"],0,[["Best","The Pleasure Principle (1979)"]]],
    thepsychedelicfurs:["The Psychedelic Furs",1981,"postpunk","Raspy, sax-laced post-punk.",["bowie","velvet"],0,[["Best","Talk Talk Talk (1981)"]]],
    simpleminds:["Simple Minds",1982,"postpunk","Anthemic Scottish new wave.",["bowie","neworder"],0,[["Best","New Gold Dream (1982)"]]],
    duranduran:["Duran Duran",1982,"postpunk","Glossy new-romantic pop-rock.",["roxymusic","bowie"],0,[["Best","Rio (1982)"]]],
    spiritualized:["Spiritualized",1997,"noise","Symphonic space-gospel.",["spacemen3","velvet"],0,[["Best","Ladies and Gentlemen We Are Floating in Space (1997)"]]],
    galaxie500:["Galaxie 500",1989,"noise","Hushed, dreamy slowcore.",["velvet"],0,[["Best","On Fire (1989)"]]],
    lush:["Lush",1992,"noise","Melodic British shoegaze.",["cocteau","mbv"],0,[["Best","Spooky (1992)"]]],
    catherinewheel:["Catherine Wheel",1992,"noise","Muscular shoegaze.",["mbv"],0,[["Best","Ferment (1992)"]]],
    mazzystar:["Mazzy Star",1993,"noise","Narcotic dream-folk.",["velvet"],0,[["Best","So Tonight That I Might See (1993)"]]],
    low:["Low",1994,"noise","Glacial slowcore pioneers.",["velvet"],0,[["Best","Things We Lost in the Fire (2001)"]]],
    yolatengo:["Yo La Tengo",1993,"noise","Versatile indie-noise institution.",["velvet","sonicyouth"],0,[["Best","I Can Hear the Heart Beating as One (1997)"]]],
    tortoise:["Tortoise",1996,"noise","Jazzy, electronic post-rock.",["can","slint"],0,[["Best","Millions Now Living Will Never Die (1996)"]]],
    aplacetoburystrangers:["A Place to Bury Strangers",2007,"noise","Brutally loud shoegaze.",["jamc","mbv"],0,[["Best","Exploding Head (2009)"]]],
    deerhunter:["Deerhunter",2008,"noise","Ambient-punk art rock.",["velvet","mbv"],0,[["Best","Halcyon Digest (2010)"]]],
    mercuryrev:["Mercury Rev",1998,"indie","Symphonic psych indie.",["flaminglips","neilyoung"],0,[["Best","Deserter's Songs (1998)"]]],
    b52s:["The B-52's",1979,"postpunk","Kitschy, danceable new-wave party rock.",["talkingheads","ramones"],0,[["Best","The B-52's (1979)"]]],
    butthole:["Butthole Surfers",1987,"noise","Deranged psychedelic noise-rock.",["stooges","blackflag"],0,[["Best","Locust Abortion Technician (1987)"]]],
    ween:["Ween",1992,"indie","Absurdist, genre-hopping cult favorites.",["beatles","beefheart"],0,[["Best","Chocolate and Cheese (1994)"]]],
    animalcollective:["Animal Collective",2007,"indie","Kaleidoscopic experimental psych-pop.",["beachboys","flaminglips"],0,[["Best","Merriweather Post Pavilion (2009)"]]],
    ofmontreal:["of Montreal",2007,"indie","Glammy, hyperactive psych-pop.",["bowie","beachboys"],0,[["Best","Hissing Fauna, Are You the Destroyer? (2007)"]]],
    mgmt:["MGMT",2008,"indie","Psychedelic synth-pop hooks.",["flaminglips","bowie"],0,[["Best","Oracular Spectacular (2007)"]]],
    bikinikill:["Bikini Kill",1992,"punk","The riot grrrl originators.",["pattismith","blackflag"],0,[["Essential","The First Two Records (1994)"]]],
    sleaterkinney:["Sleater-Kinney",1997,"punk","Fierce, interlocking riot-grrrl-bred punk.",["pattismith","bikinikill"],0,[["Best","Dig Me Out (1997)"],["Loved","The Woods (2005)"]]],
    garbage:["Garbage",1995,"indie","Sleek, dark 90s alt-rock.",["pixies","siouxsie"],0,[["Best","Garbage (1995)"]]],
    cranberries:["The Cranberries",1993,"indie","Lilting, aching Irish alt-rock.",["smiths","siouxsie"],0,[["Best","No Need to Argue (1994)"]]],
    cagetheelephant:["Cage the Elephant",2011,"indie","Scruffy, energetic modern alt-rock.",["pixies","stooges"],0,[["Best","Melophobia (2013)"]]],
    carseatheadrest:["Car Seat Headrest",2016,"indie","Wry, sprawling lo-fi indie rock.",["gbv","pavement"],0,[["Best","Teens of Denial (2016)"]]],
    mitski:["Mitski",2016,"indie","Stark, cathartic indie art-pop.",["pixies","pjharvey"],0,[["Best","Puberty 2 (2016)"],["Loved","Be the Cowboy (2018)"]]],
    boygenius:["boygenius",2018,"indie","Confessional modern indie supergroup.",["nmh","bigthief"],0,[["Best","the record (2023)"]]],
    japanesebreakfast:["Japanese Breakfast",2017,"indie","Shimmering, bittersweet indie pop.",["mbv","wilco"],0,[["Best","Jubilee (2021)"]]],
    thedistillers:["The Distillers",2003,"punk","Snarling, tough melodic punk.",["clash","badreligion"],0,[["Best","Coral Fang (2003)"]]],
    japandroids:["Japandroids",2012,"punk","Anthemic, full-throttle garage-punk.",["replacements","husker"],0,[["Best","Celebration Rock (2012)"]]],
    pup:["PUP",2016,"punk","Rowdy, chaotic pop-punk.",["descendents","greenday"],0,[["Best","The Dream Is Over (2016)"]]],
    alicecooper:["Alice Cooper",1971,"glam","The original shock-rock showman.",["stooges","doors"],0,[["Best","Billion Dollar Babies (1973)"],["Loved","Love It to Death (1971)"]]],
    u2:["U2",1980,"hardrock","Anthemic, chiming stadium rock born from post-punk.",["joydiv","television"],0,[["Best","Achtung Baby (1991)"],["Loved","The Joshua Tree (1987)"]]],
    police:["The Police",1978,"postpunk","Reggae-inflected new-wave rock.",["clash"],0,[["Best","Synchronicity (1983)"]]],
    fleetwoodmac:["Fleetwood Mac",1975,"hardrock","British blues that became soft-rock's biggest band.",["muddywaters","stones"],0,[["Best","Rumours (1977)"]]],
    bonjovi:["Bon Jovi",1986,"glam","Polished arena hair-rock.",["aerosmith","defleppard"],0,[["Best","Slippery When Wet (1986)"]]],
    direstraits:["Dire Straits",1978,"hardrock","Understated, virtuosic roots-rock.",["dylan"],0,[["Best","Brothers in Arms (1985)"]]],
    journey:["Journey",1981,"hardrock","Soaring, melodic arena rock.",[],0,[["Best","Escape (1981)"]]],
    boston:["Boston",1976,"hardrock","Meticulous, layered arena rock.",[],0,[["Best","Boston (1976)"]]],
    foreigner:["Foreigner",1977,"hardrock","Hook-heavy arena rock.",[],0,[["Best","4 (1981)"]]],
    faces:["Faces",1971,"hardrock","Raggedy, boozy British rock.",["stones","smallfaces"],0,[["Best","A Nod Is as Good as a Wink (1971)"]],"Featured Rod Stewart and Ronnie Wood, later of the Rolling Stones."],
    styx:["Styx",1977,"prog","Pomp-rock and prog-tinged arena rock.",["yes"],0,[["Best","The Grand Illusion (1977)"]]],
    kansas:["Kansas",1976,"prog","American symphonic prog rock.",["yes"],0,[["Best","Leftoverture (1976)"]]],
    steelydan:["Steely Dan",1974,"prog","Slick, jazzy studio-rock.",[],0,[["Best","Aja (1977)"]]],
    santana:["Santana",1969,"sixties","Latin-rock pioneers.",[],0,[["Best","Abraxas (1970)"]]],
    wings:["Wings",1973,"sixties","McCartney's tuneful post-Beatles band.",["beatles"],0,[["Best","Band on the Run (1973)"]],"Paul McCartney's band after the Beatles."],
    doobiebrothers:["The Doobie Brothers",1973,"southern","Harmony-rich roots and boogie rock.",[],0,[["Best","The Captain and Me (1973)"]]],
    meatloaf:["Meat Loaf",1977,"glam","Bombastic, theatrical rock opera.",[],0,[["Best","Bat Out of Hell (1977)"]]],
    petergabriel:["Peter Gabriel",1980,"indie","Arty, worldbeat-infused solo rock.",["genesis"],0,[["Best","So (1986)"]],"The original frontman of Genesis."],
    thekillers:["The Killers",2004,"indie","New-wave-fed indie arena rock.",["neworder","springsteen"],0,[["Best","Hot Fuss (2004)"]]],
    the1975:["The 1975",2013,"indie","Glossy, eclectic pop-rock.",["talkingheads","neworder"],0,[["Best","A Brief Inquiry into Online Relationships (2018)"]]],
    twentyonepilots:["Twenty One Pilots",2015,"indie","Genre-melting alt-pop-rock.",[],0,[["Best","Blurryface (2015)"]]],
    falloutboy:["Fall Out Boy",2005,"punk","Arena-sized emo-pop-punk.",["greenday","descendents"],0,[["Best","From Under the Cork Tree (2005)"]]],
    panicatthedisco:["Panic! at the Disco",2005,"punk","Baroque, theatrical emo-pop.",["falloutboy","queen"],0,[["Best","A Fever You Can't Sweat Out (2005)"]]],
    whitezombie:["White Zombie",1992,"metal","Horror-schlock groove metal.",["alicecooper","sabbath"],0,[["Best","La Sexorcisto: Devil Music, Vol. 1 (1992)"]],"Fronted by Rob Zombie."],
    marilynmanson:["Marilyn Manson",1996,"experimental","Industrial shock-rock spectacle.",["alicecooper","nin"],0,[["Best","Antichrist Superstar (1996)"]]],
    disturbed:["Disturbed",2000,"metal","Chugging, anthemic nu-metal.",["korn","pantera"],0,[["Best","The Sickness (2000)"]]],
    avengedsevenfold:["Avenged Sevenfold",2005,"metal","Theatrical metalcore turned classic metal.",["metallica","ironmaiden"],0,[["Best","City of Evil (2005)"]]],
    bringmethehorizon:["Bring Me the Horizon",2013,"metal","Deathcore turned genre-melting pop-metal.",["linkinpark","killswitch"],0,[["Best","Sempiternal (2013)"]]],
    elo:["Electric Light Orchestra",1974,"prog","Symphonic, Beatles-esque pop-rock.",["beatles"],0,[["Best","Out of the Blue (1977)"]]],
    supertramp:["Supertramp",1974,"prog","Melodic, keyboard-driven art-rock.",[],0,[["Best","Crime of the Century (1974)"]]],
    moodyblues:["The Moody Blues",1967,"prog","Orchestral, symphonic proto-prog.",["beatles"],0,[["Best","Days of Future Passed (1967)"]]],
    chicago:["Chicago",1969,"hardrock","Horn-driven jazz-rock turned soft-rock.",[],0,[["Best","Chicago Transit Authority (1969)"]]],
    toto:["Toto",1978,"hardrock","Polished, virtuosic AOR.",[],0,[["Best","Toto IV (1982)"]]],
    blackcrowes:["The Black Crowes",1990,"hardrock","Rootsy, Stones-y hard-rock revival.",["stones","faces"],0,[["Best","The Southern Harmony and Musical Companion (1992)"]]],
    zappa:["Frank Zappa",1966,"indie","Prolific avant-rock satirist and virtuoso.",[],0,[["Best","Hot Rats (1969)"]]],
    tearsforfears:["Tears for Fears",1983,"postpunk","Lush, ambitious synth-pop-rock.",["talkingheads","bowie"],0,[["Best","Songs from the Big Chair (1985)"]]],
    inxs:["INXS",1982,"postpunk","Funky Australian new-wave rock.",["stones"],0,[["Best","Kick (1987)"]]],
    midnightoil:["Midnight Oil",1982,"postpunk","Fierce, political Australian rock.",["clash"],0,[["Best","Diesel and Dust (1987)"]]],
    menatwork:["Men at Work",1981,"postpunk","Quirky, tuneful Australian new wave.",["police"],0,[["Best","Business as Usual (1981)"]]],
    crowdedhouse:["Crowded House",1986,"postpunk","Sublime melodic pop-rock.",["beatles"],0,[["Best","Woodface (1991)"]]],
    theverve:["The Verve",1993,"indie","Swirling, anthemic Britpop.",["stoneroses"],0,[["Best","Urban Hymns (1997)"]]],
    manics:["Manic Street Preachers",1992,"indie","Political, literate rock.",["clash"],0,[["Best","The Holy Bible (1994)"]]],
    supergrass:["Supergrass",1995,"indie","Punchy, youthful Britpop.",["kinks"],0,[["Best","I Should Coco (1995)"]]],
    elastica:["Elastica",1994,"indie","Wiry, post-punk-fed Britpop.",["wire","blondie"],0,[["Best","Elastica (1995)"]]],
    happymondays:["Happy Mondays",1988,"indie","Baggy Madchester groove-rock.",[],0,[["Best","Pills 'n' Thrills and Bellyaches (1990)"]]],
    charlatans:["The Charlatans",1990,"indie","Organ-led Madchester indie.",["stoneroses"],0,[["Best","Tellin' Stories (1997)"]]],
    seahorses:["The Seahorses",1997,"indie","Melodic, guitar-led Britpop.",["stoneroses"],0,[["Best","Do It Yourself (1997)"]],"Formed by the Stone Roses' John Squire."],
    spoon:["Spoon",2001,"indie","Lean, sharp, groove-driven indie rock.",["pixies","wire"],0,[["Best","Ga Ga Ga Ga Ga (2007)"]]],
    decemberists:["The Decemberists",2005,"indie","Literary, ornate indie folk-rock.",["nmh","smiths"],0,[["Best","Picaresque (2005)"]]],
    grizzlybear:["Grizzly Bear",2009,"indie","Intricate, harmony-rich baroque indie.",["beachboys","radiohead"],0,[["Best","Veckatimest (2009)"]]],
    warondrugs:["The War on Drugs",2014,"indie","Heartland rock through a shoegaze haze.",["springsteen","neilyoung"],0,[["Best","Lost in the Dream (2014)"]]],
    kurtvile:["Kurt Vile",2011,"indie","Hazy, rambling lo-fi guitar rock.",["pavement","neilyoung"],0,[["Best","Smoke Ring for My Halo (2011)"]]],
    atlassound:["Atlas Sound",2009,"noise","Woozy, textured bedroom psych.",["mbv","velvet"],0,[["Best","Logos (2009)"]],"The solo project of Deerhunter's Bradford Cox."],
    pond:["Pond",2017,"garage","Freewheeling Aussie psych-rock.",["flaminglips","tame"],0,[["Best","The Weather (2017)"]]],
    theeohsees:["Thee Oh Sees",2013,"garage","Prolific, frantic garage-psych-punk.",["stooges","sonics"],0,[["Best","Floating Coffin (2013)"]]],
    fuzz:["Fuzz",2013,"garage","Ty Segall's heavy garage-metal trio.",["sabbath","stooges"],0,[["Best","Fuzz (2013)"]]],
    blackangels:["The Black Angels",2006,"garage","Droning, dark psychedelic rock.",["velvet","elevators"],0,[["Best","Passover (2006)"]]],
    bjm:["The Brian Jonestown Massacre",1996,"garage","Sprawling neo-psychedelic revivalists.",["velvet","stones"],0,[["Best","Their Satanic Majesties' Second Request (1996)"]]],
    dandywarhols:["The Dandy Warhols",2000,"garage","Druggy, hooky neo-psych indie.",["velvet","stones"],0,[["Best","Thirteen Tales from Urban Bohemia (2000)"]]],
    takingbacksunday:["Taking Back Sunday",2002,"punk","Dueling-vocal emo drama.",["sdre","jimmyeatworld"],0,[["Best","Tell All Your Friends (2002)"]]],
    savestheday:["Saves the Day",1999,"punk","Melodic, breakneck emo-punk.",["descendents","jimmyeatworld"],0,[["Best","Through Being Cool (1999)"]]],
    braid:["Braid",1998,"punk","Angular Midwest emo.",["capnjazz","sdre"],0,[["Best","Frame & Canvas (1998)"]]],
    texasisthereason:["Texas Is the Reason",1996,"punk","Melodic, influential post-hardcore emo.",["sdre","fugazi"],0,[["Best","Do You Know Who You Are? (1996)"]]],
    dashboard:["Dashboard Confessional",2001,"punk","Confessional acoustic emo.",["sdre","jimmyeatworld"],0,[["Best","The Places You Have Come to Fear the Most (2001)"]]],
    afi:["AFI",2003,"punk","Hardcore that morphed into goth-punk.",["misfits","badreligion"],0,[["Best","Sing the Sorrow (2003)"]]],
    theused:["The Used",2002,"punk","Screamy, cathartic emo.",["sdre","mcr"],0,[["Best","The Used (2002)"]]],
    blink182:["Blink-182",1999,"punk","Snotty, hooky pop-punk juggernaut.",["descendents","greenday"],0,[["Best","Enema of the State (1999)"]]],
    sum41:["Sum 41",2001,"punk","Bratty pop-punk with metal flashes.",["greenday","offspring"],0,[["Best","All Killer No Filler (2001)"]]],
    goodcharlotte:["Good Charlotte",2002,"punk","Mall-punk anthems.",["greenday","blink182"],0,[["Best","The Young and the Hopeless (2002)"]]],
    simpleplan:["Simple Plan",2002,"punk","Earnest, radio-ready pop-punk.",["blink182","greenday"],0,[["Best","No Pads, No Helmets... Just Balls (2002)"]]],
    coheed:["Coheed and Cambria",2003,"punk","Sci-fi prog-emo epics.",["marsvolta","rush"],0,[["Best","In Keeping Secrets of Silent Earth: 3 (2003)"]]],
    riseagainst:["Rise Against",2004,"punk","Melodic, political hardcore-punk.",["badreligion","minorthreat"],0,[["Best","Siren Song of the Counter Culture (2004)"]]],
    mrbungle:["Mr. Bungle",1991,"metal","Deranged avant-garde funk-metal.",["faithnomore","zappa"],0,[["Best","Mr. Bungle (1991)"]],"Mike Patton's band alongside Faith No More."],
    helmet:["Helmet",1992,"metal","Precise, groove-heavy alt-metal.",["blackflag","sabbath"],0,[["Best","Meantime (1992)"]]],
    livingcolour:["Living Colour",1988,"metal","Virtuosic funk-metal.",["hendrix","badbrains"],0,[["Best","Vivid (1988)"]]],
    incubus:["Incubus",2001,"metal","Funk-metal turned melodic alt-rock.",["faithnomore","rhcp"],0,[["Best","Morning View (2001)"]]],
    velvetrevolver:["Velvet Revolver",2004,"hardrock","Hard-rock supergroup.",["gunsnroses","stp"],0,[["Best","Contraband (2004)"]],"Guns N' Roses members with STP's Scott Weiland."],
    threeoneone:["311",1995,"metal","Reggae-and-funk-tinged rap-rock.",["rhcp","badbrains"],0,[["Best","311 (1995)"]]],
    evanescence:["Evanescence",2003,"metal","Gothic symphonic nu-metal.",["korn","tool"],0,[["Best","Fallen (2003)"]]],
    threedaysgrace:["Three Days Grace",2006,"metal","Brooding post-grunge alt-metal.",["korn","disturbed"],0,[["Best","One-X (2006)"]]],
    breakingbenjamin:["Breaking Benjamin",2006,"metal","Heavy, melodic post-grunge.",["tool","stp"],0,[["Best","Phobia (2006)"]]],
    nickelback:["Nickelback",2001,"metal","Ubiquitous post-grunge hard rock.",["pearljam","metallica"],0,[["Best","Silver Side Up (2001)"]]],
    him:["HIM",2000,"postpunk","Finnish gothic love-metal.",["sistersofmercy","depechemode"],0,[["Best","Razorblade Romance (2000)"]]],
    dragonforce:["DragonForce",2006,"metal","Hyperspeed power metal.",["ironmaiden"],0,[["Best","Inhuman Rampage (2006)"]]],
    bfmv:["Bullet for My Valentine",2005,"metal","Melodic Welsh metalcore.",["metallica","killswitch"],0,[["Best","The Poison (2005)"]]],
    cake:["Cake",1996,"indie","Deadpan, horn-tinged alt-rock.",[],0,[["Best","Fashion Nugget (1996)"]]],
    lemonheads:["The Lemonheads",1992,"indie","Scruffy, melodic alt-rock.",["replacements","husker"],0,[["Best","It's a Shame About Ray (1992)"]]],
    failure:["Failure",1996,"indie","Heavy, spacey alt-rock.",["sonicyouth","pixies"],0,[["Best","Fantastic Planet (1996)"]]],
    hum:["Hum",1995,"indie","Crushing, cosmic space-rock.",["dinosaurjr","mbv"],0,[["Best","You'd Prefer an Astronaut (1995)"]]],
    shiner:["Shiner",2001,"punk","Melodic, heavy space-rock post-hardcore.",["jawbox"],0,[["Best","The Egg (2001)"]]],
    socialdistortion:["Social Distortion",1990,"punk","Rootsy, tattooed SoCal punk.",["ramones","x"],0,[["Best","Social Distortion (1990)"]]],
    pennywise:["Pennywise",1995,"punk","Fast, anthemic melodic hardcore.",["badreligion","minorthreat"],0,[["Best","About Time (1995)"]]],
    wolfmother:["Wolfmother",2005,"hardrock","Retro, riff-heavy hard rock.",["sabbath","ledzep"],0,[["Best","Wolfmother (2005)"]]],
    jet:["Jet",2003,"garage","Swaggering garage-rock revival.",["acdc","stooges"],0,[["Best","Get Born (2003)"]]],
    keane:["Keane",2004,"indie","Piano-led anthemic pop-rock.",["beatles"],0,[["Best","Hopes and Fears (2004)"]]],
    kaiserchiefs:["Kaiser Chiefs",2005,"indie","Rowdy, post-punk-fed Britpop.",["blur","thejam"],0,[["Best","Employment (2005)"]]],
    hothotheat:["Hot Hot Heat",2002,"postpunk","Herky-jerky dance-punk.",["thecure","franzferdinand"],0,[["Best","Make Up the Breakdown (2002)"]]],
    therapture:["The Rapture",2003,"postpunk","Cowbell-driven dance-punk.",["gangoffour","lcd"],0,[["Best","Echoes (2003)"]]],
    phoenix:["Phoenix",2009,"indie","Sleek French indie-pop-rock.",[],0,[["Best","Wolfgang Amadeus Phoenix (2009)"]]],
    theshins:["The Shins",2001,"indie","Bright, literate indie-pop.",["beachboys","smiths"],0,[["Best","Oh, Inverted World (2001)"]]],
    mymorningjacket:["My Morning Jacket",2005,"indie","Reverb-soaked cosmic Americana.",["neilyoung","flaminglips"],0,[["Best","Z (2005)"]]],
    bandofhorses:["Band of Horses",2006,"indie","Big-sky indie-folk-rock.",["neilyoung","nmh"],0,[["Best","Everything All the Time (2006)"]]],
    thirtystm:["30 Seconds to Mars",2005,"indie","Anthemic, arena-scaled alt-rock.",["tool","u2"],0,[["Best","A Beautiful Lie (2005)"]]],
    royorbison:["Roy Orbison",1960,"roots","Operatic, dramatic rock-and-roll balladry.",["elvis"],0,[["Comp","The Monument Singles"]]],
    dickdale:["Dick Dale",1962,"garage","The thunderous king of surf guitar.",["linkwray"],0,[["Best","Surfers' Choice (1962)"]]],
    tbonewalker:["T-Bone Walker",1947,"roots","Pioneering electric blues guitarist.",[],0,[["Comp","The Complete Imperial Recordings"]]],
    thetroggs:["The Troggs",1966,"garage","Primitive, lusty garage-rock.",["kinks"],0,[["Best","From Nowhere (1966)"]]],
    traffic:["Traffic",1967,"sixties","Jazzy, folky psychedelic rock.",["beatles"],0,[["Best","John Barleycorn Must Die (1970)"]]],
    bigbrother:["Big Brother & the Holding Company",1968,"sixties","Janis Joplin's raw psychedelic blues-rock.",["muddywaters"],0,[["Best","Cheap Thrills (1968)"]]],
    theseeds:["The Seeds",1966,"garage","Snarling garage-punk progenitors.",[],0,[["Best","The Seeds (1966)"]]],
    flyingburrito:["The Flying Burrito Brothers",1969,"southern","Gram Parsons' cosmic country-rock.",["byrds","gramparsons"],0,[["Best","The Gilded Palace of Sin (1969)"]]],
    thejayhawks:["The Jayhawks",1992,"southern","Harmony-rich alt-country.",["gramparsons","neilyoung"],0,[["Best","Hollywood Town Hall (1992)"]]],
    sonvolt:["Son Volt",1995,"southern","Rootsy, melancholy alt-country.",["uncletupelo","neilyoung"],0,[["Best","Trace (1995)"]]],
    steveearle:["Steve Earle",1986,"southern","Gritty, literate country-rock.",["springsteen"],0,[["Best","Guitar Town (1986)"]]],
    mountain:["Mountain",1970,"hardrock","Heavy, riff-driven proto-metal.",["cream"],0,[["Best","Climbing! (1970)"]]],
    grandfunk:["Grand Funk Railroad",1970,"hardrock","Loud, populist American hard rock.",["cream"],0,[["Best","Closer to Home (1970)"]]],
    free:["Free",1969,"hardrock","Spare, soulful blues-rock.",["cream"],0,[["Best","Fire and Water (1970)"]]],
    whitesnake:["Whitesnake",1984,"glam","Bluesy hard rock turned hair-metal.",["deeppurple","ledzep"],0,[["Best","Whitesnake (1987)"]]],
    tednugent:["Ted Nugent",1975,"hardrock","Wild, high-energy guitar rock.",[],0,[["Best","Ted Nugent (1975)"]]],
    helloween:["Helloween",1985,"metal","The originators of power metal.",["ironmaiden","judaspriest"],0,[["Best","Keeper of the Seven Keys (1987)"]]],
    blindguardian:["Blind Guardian",1992,"metal","Epic, layered German power metal.",["helloween","ironmaiden"],0,[["Best","Somewhere Far Beyond (1992)"]]],
    manowar:["Manowar",1984,"metal","Bombastic, muscular true metal.",["sabbath"],0,[["Best","Kings of Metal (1988)"]]],
    machinehead:["Machine Head",1994,"metal","Pummeling groove metal.",["pantera","slayer"],0,[["Best","Burn My Eyes (1994)"]]],
    fearfactory:["Fear Factory",1995,"experimental","Machine-precise industrial metal.",["ministry","slayer"],0,[["Best","Demanufacture (1995)"]]],
    inflames:["In Flames",1999,"metal","Melodic Gothenburg death metal.",["atthegates"],0,[["Best","Colony (1999)"]]],
    behemoth:["Behemoth",2004,"metal","Blackened death-metal spectacle.",["mayhem","morbidangel"],0,[["Best","The Satanist (2014)"]]],
    betweenburied:["Between the Buried and Me",2007,"metal","Sprawling, proggy metalcore.",["dreamtheater","converge"],0,[["Best","Colors (2007)"]]],
    animalsasleaders:["Animals as Leaders",2011,"metal","Virtuosic instrumental djent.",["meshuggah"],0,[["Best","Weightless (2011)"]]],
    pallbearer:["Pallbearer",2014,"metal","Mournful, melodic doom.",["sabbath","candlemass"],0,[["Best","Foundations of Burden (2014)"]]],
    sunno:["Sunn O)))",2005,"metal","Monolithic drone-metal.",["melvins","sabbath"],0,[["Best","Monoliths & Dimensions (2009)"]]],
    typeonegative:["Type O Negative",1993,"postpunk","Lugubrious, romantic goth-metal.",["sabbath","sistersofmercy"],0,[["Best","Bloody Kisses (1993)"]]],
    minutemen:["Minutemen",1984,"punk","Terse, funky, political SST punk.",["blackflag"],0,[["Best","Double Nickels on the Dime (1984)"]]],
    discharge:["Discharge",1982,"punk","The originators of D-beat hardcore.",["pistols"],0,[["Essential","Hear Nothing See Nothing Say Nothing (1982)"]]],
    crass:["Crass",1978,"punk","Uncompromising anarcho-punk.",["pistols"],0,[["Best","The Feeding of the 5000 (1978)"]]],
    theexploited:["The Exploited",1981,"punk","Blistering UK street punk.",["pistols","discharge"],0,[["Best","Punks Not Dead (1981)"]]],
    adolescents:["Adolescents",1981,"punk","Melodic SoCal hardcore.",["blackflag"],0,[["Best","Adolescents (1981)"]]],
    drivelikejehu:["Drive Like Jehu",1994,"punk","Sprawling, frantic post-hardcore.",["fugazi"],0,[["Best","Yank Crime (1994)"]]],
    hotsnakes:["Hot Snakes",2000,"punk","Terse, driving post-punk-hardcore.",["drivelikejehu","wire"],0,[["Best","Automatic Midnight (2000)"]]],
    unwound:["Unwound",1995,"noise","Bleak, dynamic noise-rock.",["sonicyouth","fugazi"],0,[["Best","Repetition (1996)"]]],
    glassjaw:["Glassjaw",2000,"punk","Volatile, influential post-hardcore.",["fugazi","deftones"],0,[["Best","Everything You Ever Wanted to Know About Silence (2000)"]]],
    thrice:["Thrice",2003,"punk","Ambitious, evolving post-hardcore.",["refused","fugazi"],0,[["Best","The Artist in the Ambulance (2003)"]]],
    underoath:["Underoath",2006,"metal","Cathartic metalcore-screamo.",["refused","thursday"],0,[["Best","Define the Great Line (2006)"]]],
    ladispute:["La Dispute",2011,"punk","Spoken-word post-hardcore.",["fugazi","thursday"],0,[["Best","Wildlife (2011)"]]],
    ceremony:["Ceremony",2012,"punk","Hardcore turned post-punk.",["blackflag","joydiv"],0,[["Best","Zoo (2012)"]]],
    neckdeep:["Neck Deep",2015,"punk","Bright Welsh pop-punk.",["blink182","greenday"],0,[["Best","Life's Not Out to Get You (2015)"]]],
    citizen:["Citizen",2013,"punk","Grungy, cathartic emo.",["sdre","nirvana"],0,[["Best","Youth (2013)"]]],
    thesound:["The Sound",1980,"postpunk","Overlooked, intense post-punk.",["joydiv"],0,[["Best","From the Lions Mouth (1981)"]]],
    theraincoats:["The Raincoats",1979,"postpunk","Scrappy, arty feminist post-punk.",["pistols"],0,[["Best","The Raincoats (1979)"]]],
    protomartyr:["Protomartyr",2015,"postpunk","Literate, brooding post-punk.",["thefall","joydiv"],0,[["Best","The Agent Intellect (2015)"]]],
    parquetcourts:["Parquet Courts",2013,"postpunk","Wry, wiry post-punk slacker rock.",["pavement","wire"],0,[["Best","Light Up Gold (2012)"]]],
    iceage:["Iceage",2014,"postpunk","Feral, arty Danish post-punk.",["joydiv","birthday"],0,[["Best","Plowing Into the Field of Love (2014)"]]],
    loop:["Loop",1987,"noise","Hypnotic, droning psych-rock.",["stooges","spacemen3"],0,[["Best","Heaven's End (1987)"]]],
    chapterhouse:["Chapterhouse",1991,"noise","Dreamy, groove-based shoegaze.",["mbv"],0,[["Best","Whirlpool (1991)"]]],
    duster:["Duster",1998,"noise","Lo-fi slowcore space-rock.",["slowdive"],0,[["Best","Stratosphere (1998)"]]],
    diiv:["DIIV",2012,"noise","Chiming, hazy modern shoegaze.",["slowdive","jamc"],0,[["Best","Oshin (2012)"]]],
    nothing:["Nothing",2014,"noise","Heavy, melodic modern shoegaze.",["mbv","deftones"],0,[["Best","Guilty of Everything (2014)"]]],
    codeine:["Codeine",1992,"noise","Glacial slowcore pioneers.",["velvet"],0,[["Best","Frigid Stars (1990)"]]],
    mono:["Mono",2004,"noise","Cinematic Japanese post-rock.",["godspeed","mogwai"],0,[["Best","You Are There (2006)"]]],
    builttospill:["Built to Spill",1997,"indie","Sprawling, guitar-drenched indie rock.",["dinosaurjr","neilyoung"],0,[["Best","Perfect from Now On (1997)"]]],
    elliottsmith:["Elliott Smith",1997,"indie","Hushed, aching songwriting.",["beatles"],0,[["Best","Either/Or (1997)"]]],
    boniver:["Bon Iver",2011,"indie","Falsetto folk turned art-pop.",["neilyoung"],0,[["Best","Bon Iver (2011)"]]],
    fleetfoxes:["Fleet Foxes",2008,"indie","Lush, harmony-rich folk-rock.",["beachboys","neilyoung"],0,[["Best","Fleet Foxes (2008)"]]],
    brokensocialscene:["Broken Social Scene",2003,"indie","Sprawling indie-rock collective.",[],0,[["Best","You Forgot It in People (2002)"]]],
    beachhouse:["Beach House",2010,"noise","Narcotic, opulent dream-pop.",["cocteau","mbv"],0,[["Best","Teen Dream (2010)"]]],
    courtneybarnett:["Courtney Barnett",2015,"indie","Deadpan, witty slacker rock.",["pavement","nirvana"],0,[["Best","Sometimes I Sit and Think, and Sometimes I Just Sit (2015)"]]],
    motherlovebone:["Mother Love Bone",1990,"grunge","Glammy proto-grunge.",["stooges","aerosmith"],0,[["Best","Apple (1990)"]]],
    madseason:["Mad Season",1995,"grunge","Bluesy grunge supergroup.",["alicechains","pearljam"],0,[["Best","Above (1995)"]]],
    l7:["L7",1992,"grunge","Snarling, heavy punk-grunge.",["stooges","blackflag"],0,[["Best","Bricks Are Heavy (1992)"]]],
    silverchair:["Silverchair",1995,"grunge","Teenage Australian grunge.",["soundgarden","nirvana"],0,[["Best","Frogstomp (1995)"]]],
    bush:["Bush",1994,"grunge","Polished British post-grunge.",["nirvana","pixies"],0,[["Best","Sixteen Stone (1994)"]]],
    creed:["Creed",1999,"grunge","Massive, earnest post-grunge.",["pearljam"],0,[["Best","Human Clay (1999)"]]],
    gretavanfleet:["Greta Van Fleet",2018,"hardrock","Zeppelin-worshipping retro rock.",["ledzep"],0,[["Best","Anthem of the Peaceful Army (2018)"]]],
    royalblood:["Royal Blood",2014,"hardrock","Bass-and-drums heavy blues-rock.",["qotsa","ledzep"],0,[["Best","Royal Blood (2014)"]]],
    maneskin:["Maneskin",2021,"glam","Flamboyant Italian glam-rock revival.",["stones","stooges"],0,[["Best","Teatro d'ira (2021)"]]],
    narrowhead:["Narrow Head",2020,"indie","Heavy 90s-style alt/grunge revival.",["hum","deftones"],0,[["Best","12th House Rock (2020)"]]],
    superheaven:["Superheaven",2015,"indie","Fuzzy, grungy alt-rock revival.",["dinosaurjr","alicechains"],0,[["Best","Ours Is Chrome (2015)"]]],
    teenagewrist:["Teenage Wrist",2018,"grunge","Fuzzy, melodic grunge-gaze.",["pumpkins","nirvana"],1,[["Best","Chrome Neon Jesus (2018)"]]],
    fleshwater:["Fleshwater",2022,"grunge","Heavy, dreamy grunge-gaze.",["superheaven","deftones"],1,[["Best","We're Not Here to Be Loved (2022)"]]],
    cloakroom:["Cloakroom",2017,"indie","Cavernous doomgaze-grunge.",["hum","nirvana"],1,[["Best","Time Well (2017)"]]],
    slowpulp:["Slow Pulp",2020,"indie","Fuzzy, downcast indie-grunge.",["pixies","nirvana"],1,[["Best","Moveys (2020)"]]],
    hotlinetnt:["Hotline TNT",2023,"noise","Blown-out, hooky shoegaze-grunge.",["mbv","dinosaurjr"],1,[["Best","Cartwheel (2023)"]]],
    balanceandcomposure:["Balance and Composure",2013,"punk","Grungy, brooding emo.",["sdre","nirvana"],1,[["Best","The Things We Think We're Missing (2013)"]]],
    turnover:["Turnover",2015,"noise","Dreamy emo turned shoegaze.",["sdre","cocteau"],1,[["Best","Peripheral Vision (2015)"]]],
    drugchurch:["Drug Church",2022,"punk","Hooky, sardonic post-hardcore.",["quicksand","husker"],1,[["Best","Hygiene (2022)"]]],
    gougeaway:["Gouge Away",2018,"punk","Pixies-fed noisy post-hardcore.",["pixies","fugazi"],1,[["Best","Burnt Sugar (2018)"]]],
    prizehorse:["Prize Horse",2024,"grunge","Heavy, melodic grunge-gaze.",["hum","nirvana"],1,[["Best","Under Sound (2024)"]]],
    sap:["Sap",2023,"grunge","Austin grunge-revival trio.",["alicechains","soundgarden"],1,[]],
    tad:["TAD",1991,"grunge","Bruising, blue-collar Sub Pop grunge.",["melvins","stooges"],0,[["Best","8-Way Santa (1991)"]]],
    chavez:["Chavez",1995,"indie","Angular, crunchy 90s alt-rock.",["pixies","dinosaurjr"],0,[["Best","Gone Glimmering (1995)"]]],
    polvo:["Polvo",1993,"noise","Warped, mathy indie noise-rock.",["sonicyouth"],0,[["Best","Today's Active Lifestyles (1993)"]]],
    girlsagainstboys:["Girls Against Boys",1996,"noise","Sleek, sinister twin-bass noise-rock.",["jesuslizard","fugazi"],0,[["Best","House of GVSB (1996)"]]],
    localh:["Local H",1996,"grunge","Two-man post-grunge crunch.",["nirvana","pixies"],0,[["Best","As Good as Dead (1996)"]]],
    seaweed:["Seaweed",1993,"grunge","Melodic Sub Pop post-hardcore-grunge.",["husker","sdre"],0,[["Best","Four (1993)"]]],
    far:["Far",1998,"punk","Melodic, heavy emo-post-hardcore.",["quicksand","deftones"],0,[["Best","Water & Solutions (1998)"]]],
    handsome:["Handsome",1997,"metal","Melodic post-Helmet alt-metal.",["helmet","quicksand"],0,[["Best","Handsome (1997)"]]],
    autolux:["Autolux",2004,"noise","Woozy, heavy noise-pop.",["mbv","sonicyouth"],0,[["Best","Future Perfect (2004)"]]],
    aperfectcircle:["A Perfect Circle",2000,"metal","Sleek, brooding alt-metal.",["tool","failure"],0,[["Best","Mer de Noms (2000)"]],"Maynard James Keenan of Tool with guitarist Billy Howerdel."],
    filter:["Filter",1995,"experimental","Melodic industrial-rock.",["nin","ministry"],0,[["Best","Short Bus (1995)"]]],
    thedismembermentplan:["The Dismemberment Plan",1999,"punk","Spastic, inventive post-hardcore indie.",["fugazi"],0,[["Best","Emergency & I (1999)"]]],
    bardopond:["Bardo Pond",1997,"noise","Narcotic, heavy psych-shoegaze.",["spacemen3","mbv"],0,[["Best","Lapsed (1997)"]]],
    medicine:["Medicine",1992,"noise","Noisy American shoegaze.",["mbv","jamc"],0,[["Best","Shot Forth Self Living (1992)"]]],
    dropnineteens:["Drop Nineteens",1992,"noise","Dreamy US shoegaze.",["mbv","slowdive"],0,[["Best","Delaware (1992)"]]],
    swirlies:["Swirlies",1993,"noise","Scrappy, lo-fi noise-shoegaze.",["mbv","pavement"],0,[["Best","Blonder Tongue Audio Baton (1993)"]]],
    fumanchu:["Fu Manchu",1996,"metal","Fuzzed-out desert stoner rock.",["kyuss","sabbath"],0,[["Best","In Search Of... (1996)"]]],
    monstermagnet:["Monster Magnet",1995,"metal","Space-rock stoner metal.",["hawkwind","sabbath"],0,[["Best","Dopes to Infinity (1995)"]]],
    elder:["Elder",2017,"metal","Progressive, expansive stoner-metal.",["sleep","kyuss"],1,[["Best","Reflections of a Floating World (2017)"]]],
    allthemwitches:["All Them Witches",2015,"metal","Bluesy, psychedelic heavy rock.",["sabbath","kyuss"],1,[["Best","Dying Surfer Meets His Maker (2015)"]]],
    uncleacid:["Uncle Acid & the Deadbeats",2013,"metal","Melodic, sinister retro doom.",["sabbath","beatles"],1,[["Best","Mind Control (2013)"]]],
    earthless:["Earthless",2007,"metal","Instrumental psychedelic heavy jam-rock.",["hendrix","sabbath"],0,[["Best","Rhythms from a Cosmic Sky (2007)"]]],
    graveyard:["Graveyard",2011,"metal","Soulful Swedish retro hard rock.",["sabbath","cream"],0,[["Best","Hisingen Blues (2011)"]]],
    windhand:["Windhand",2013,"metal","Doom-laden, melodic sludge.",["sabbath","electricwizard"],1,[["Best","Soma (2013)"]]],
    basement:["Basement",2012,"punk","Grungy British emo.",["sdre","nirvana"],1,[["Best","Colourmeinkindness (2012)"]]],
    ovlov:["Ovlov",2013,"indie","Fuzzy, melodic grunge-indie.",["dinosaurjr","nirvana"],1,[["Best","am (2013)"]]],
    pitysex:["Pity Sex",2013,"noise","Fuzzy shoegaze-emo.",["mbv","nirvana"],1,[["Best","Feast of Love (2013)"]]],
    whirr:["Whirr",2014,"noise","Heavy, hazy shoegaze.",["mbv","slowdive"],1,[["Best","Sway (2014)"]]],
    fiddlehead:["Fiddlehead",2018,"punk","Melodic, urgent post-hardcore.",["husker","sdre"],1,[["Best","Springtime and Blind (2018)"]]],
    truthcult:["Truth Cult",2022,"punk","Melodic, driving modern hardcore.",["turnstile","badbrains"],1,[["Best","Walk the Wheel (2022)"]]],
    slowcrush:["Slow Crush",2018,"noise","Heavy Belgian shoegaze.",["slowdive","nothing"],1,[["Best","Aurora (2018)"]]],
    feeblelittlehorse:["Feeble Little Horse",2023,"indie","Noisy, playful lo-fi indie-grunge.",["pavement","dinosaurjr"],1,[["Best","Girl with Fish (2023)"]]],
    sensefield:["Sensefield",1996,"punk","Melodic post-hardcore and emo.",["quicksand","sdre"],0,[["Best","Building (1996)"]]],
    bitchmagnet:["Bitch Magnet",1990,"noise","Heavy, mathy noise-rock.",["slint","husker"],0,[["Best","Ben Hur (1990)"]]],
    torche:["Torche",2008,"metal","Melodic sludge-pop-metal.",["melvins","sabbath"],0,[["Best","Meanderthal (2008)"]]]
  };

window.INFLUENCE_DATA = { GEN: GEN, RAW: RAW };
